moved tfbuild from master.yml to scripts

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -1089,6 +1089,119 @@ terraform_apply_and_push() {
   set +e
 }
 
+terraform_build() {
+  set -e
+  modifiedDir
+  BASE_DIR=$PWD
+  BUILD_DIR=$BASE_DIR/build
+  mkdir -p $BUILD_DIR
+  DIRECTORIES=$(modifiedDir)
+  EXCLUDE_DIR=("build",".github",".gitignore","convoy.yaml","README.md","ci-scripts")
+  for DIR in $DIRECTORIES
+  do
+    if [[ " ${EXCLUDE_DIR[*]} " != *"$DIR"* ]]; then 
+      echo "building  ${DIR}"
+      ARTIFACT_FILE=$BUILD_DIR/${DIR}.zip
+      cd $BASE_DIR/$DIR
+      VERSION=$(yq .version convoy.yaml)
+      if yq eval '.externalUrls' convoy.yaml &> /dev/null; then
+        echo "externalUrls present in convoy.yaml. Downloading required binaries."
+        urls=$(yq eval '.externalUrls[]' convoy.yaml)
+        for url in ${urls}; do
+          echo "Processing URL: ${url}"
+          filename=$(basename "${url}")
+          wget "${url}" 
+          unzip "${filename}"
+          rm "${filename}"
+          echo "Downloaded and extracted: ${filename}"
+        done
+      fi
+      echo terraform_build $BASE_DIR/$DIR $ARTIFACT_FILE
+      terraform_build $PWD $ARTIFACT_FILE
+    fi
+  done
+  ls -lrta $BUILD_DIR
+  set +e
+}
+
+
+terraform_build_and_push() {
+  set -e
+  BASE_DIR=$PWD
+  BUILD_DIR=$BASE_DIR/build
+  mkdir -p $BUILD_DIR
+  DIRECTORIES=($(ls -d */))
+  EXCLUDE_DIR=("build",".github",".gitignore","convoy.yaml","README.md","ci-scripts")
+  MODIFIED_DIRECTORIES=$(modifiedDir)
+  if [[ ${BASE_BRANCH} == 'main' ]]; then
+    manifestLabel="latest-main"
+  else 
+    manifestLabel="${LABEL}"
+  fi
+  releaseManifest=$(curl --silent --location "${{env.RELEASE_MANIFEST_URL}}/${manifestLabel}")
+  for DIR in "${DIRECTORIES[@]}"; do
+    CHECKSUM=""
+    DIR=${DIR%/}
+    if [[ ! " $MODIFIED_DIRECTORIES " =~ " $DIR " && " ${EXCLUDE_DIR[*]} " != *"$DIR"* ]]; then
+      CHECKSUM=$(echo "$releaseManifest" | jq -r ".artifacts[\"${DIR}\"].checksum // empty")
+      if [[ -n ${CHECKSUM} ]]; then
+        echo "Checksum already present in release manifest for tf module: ${DIR}."
+        ARTIFACT_CHECKSUMS+="${DIR}:${CHECKSUM}%"           
+      else
+        echo "Checksum not present in release manifest for tf-module: ${DIR}. Building the module and generating checksum."
+        ARTIFACT_FILE="${DIR}.zip"
+        cd $BASE_DIR/$DIR
+        VERSION=$(yq .version convoy.yaml)
+        terraform_build $PWD $BUILD_DIR/$ARTIFACT_FILE
+        cd $BASE_DIR
+        generateChecksum "$ARTIFACT_FILE"
+      fi
+    fi
+  done
+  for DIR in $MODIFIED_DIRECTORIES
+  do
+    if [[ " ${EXCLUDE_DIR[*]} " != *"$DIR"* ]]; then 
+      ARTIFACT_FILE=${DIR}.zip
+      cd $BASE_DIR/$DIR
+      VERSION=$(yq .version convoy.yaml)
+      if yq eval '.externalUrls' convoy.yaml &> /dev/null; then
+        echo "externalUrls present in convoy.yaml. Downloading required binaries."
+        urls=$(yq eval '.externalUrls[]' convoy.yaml)
+        for url in ${urls}; do
+          echo "Processing URL: ${url}"
+          filename=$(basename "${url}")
+          wget "${url}" 
+          unzip "${filename}"
+          rm "${filename}"
+          echo "Downloaded and extracted: ${filename}"
+        done
+      fi
+      terraform_build $PWD $BUILD_DIR/$ARTIFACT_FILE
+      cd $BASE_DIR
+      generateChecksum "$ARTIFACT_FILE"
+      ARTIFACT_FILE=$BUILD_DIR/${DIR}.zip
+      if [[ ${APP_GROUP} == ${TESSELL_GCP_APP_NAME} ]]; then
+        push_to_gcloud "$ARTIFACT_FILE" "gs://tessellgcp-artifacts/${LABEL}/$DIR/$DIR-$VERSION.zip"
+      else
+        mvnDeploy "$DIR" "zip" "$ARTIFACT_FILE" "tessell.terraform_modules" "$VERSION"
+        awsConfigureDevqaInfra
+        aws s3 cp "$ARTIFACT_FILE" "s3://tessell-terraform-modules-terls/$DIR/$VERSION/"
+        pushToNexus "$ARTIFACT_FILE" "${{env.NEXUS_ARTIFACT_REPO}}/${LABEL}/$DIR/$DIR-$VERSION.zip"
+        configureAndPushAWS ${AWS_ACCOUNT_TESSELL_DEV} ${TESSELL_ARTIFACTS_TF_DEV_S3} "$ARTIFACT_FILE" "s3://${TESSELL_ARTIFACTS_TF_DEV_S3}/${LABEL}/$DIR/$DIR-$VERSION.zip"
+        configureAndPushAWS ${AWS_ACCOUNT_TESSELL_QA} ${TESSELL_ARTIFACTS_TF_QA_S3} "$ARTIFACT_FILE" "s3://${TESSELL_ARTIFACTS_TF_QA_S3}/${LABEL}/$DIR/$DIR-$VERSION.zip"
+        configureAndPushAWS ${AWS_ACCOUNT_TESSELL_STAGE} ${TESSELL_ARTIFACTS_TF_STAGE_S3} "$ARTIFACT_FILE" "s3://${TESSELL_ARTIFACTS_TF_STAGE_S3}/${LABEL}/$DIR/$DIR-$VERSION.zip"
+        configureAndPushAWS ${AWS_ACCOUNT_TESSELL_PROD} ${TESSELL_ARTIFACTS_TF_PROD_S3} "$ARTIFACT_FILE" "s3://${TESSELL_ARTIFACTS_TF_PROD_S3}/${LABEL}/$DIR/$DIR-$VERSION.zip"
+        for env in "${environments[@]}"
+        do
+          pushToMinio "$ARTIFACT_FILE" "minio-ci/tessell-artifacts-$env/${LABEL}/$DIR/$DIR-$VERSION.zip"
+        done
+      fi
+    fi
+  done
+  ls -lrta $BUILD_DIR
+  set +e
+}
+
 terraform_zip_build() {
   set -e
   ARTIFACT="${1}"
