TDEVOPS-1211 | Allow `.buildTool` & `.buildAndPushFunction` in convoy.yaml

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -103,17 +103,16 @@ check_flyway() {
 
 configure_go_version() {
   required_go_version=$(get_required_go_version)
+  [[ -n ${required_go_version:-} ]] || return
   if ! is_go_version_installed ${required_go_version}; then
     echo "Go lang version ${required_go_version} is not installed."
     gvm install ${required_go_version}
   fi
   gvm use ${required_go_version}
   export GOROOT="/home/github/.gvm/versions/go${required_go_version}.linux.amd64"
-  export GOPATH="/home/github/.gvm/versions/go${required_go_version}"
-  export PATH="${GOROOT}/bin:${GOPATH}/bin:$PATH"
-  echo ${GOROOT}
-  echo ${GOPATH}
-  echo ${PATH}
+  export PATH="${GOROOT}/bin:${PATH}"
+  echo "GOROOT = ${GOROOT}"
+  echo "PATH = ${PATH}"
   go version
 }
 
@@ -459,8 +458,10 @@ get_previous_commited_software_manifest() {
 get_required_go_version() {
   check_convoy_yaml
   required_go_version=$(yq e '.goVersion // ""' convoy.yaml 2>/dev/null)
-  if [[ -n "${required_go_version}" ]]; then
-    echo "Go version declared in convoy.yaml: ${required_go_version}"  >&2
+  if [[ -n ${required_go_version} ]]; then
+    echo "Go version declared in convoy.yaml: ${required_go_version}" >&2
+  elif [[ -n ${GOROOT:-} ]]; then
+    echo "GOROOT is already set and convoy.yaml doesn't have 'goVersion' declared" >&2
   else
     runner=$(yq e '.runner // ""' convoy.yaml)
     case "$runner" in
@@ -469,7 +470,7 @@ get_required_go_version() {
       amd-go-21) required_go_version="1.21.5" ;;
       amd-go-22) required_go_version="1.22.7" ;;
       *) 
-        echo "Error: Unknown runner value '${runner}'!"  >&2
+        echo "Error: Unknown runner value '${runner}'!" >&2
         exit 1
         ;;
     esac
diff --git a/.github/workflows/master_build_merge.yml b/.github/workflows/master_build_merge.yml
--- a/.github/workflows/master_build_merge.yml
+++ b/.github/workflows/master_build_merge.yml
@@ -51,6 +51,7 @@ jobs:
       AWS_ACCOUNT_TESSELL_STAGE: ${{vars.AWS_ACCOUNT_TESSELL_STAGE}}
       AWS_ACCOUNT_TESSELL_PROD: ${{vars.AWS_ACCOUNT_TESSELL_PROD}}
       BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
+      BUILD_PHASE: post-merge
       CI_BRANCH: main
       CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
       CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
@@ -224,6 +225,7 @@ jobs:
       AWS_ACCOUNT_TESSELL_PROD: ${{vars.AWS_ACCOUNT_TESSELL_PROD}}
       AWS_EC2_METADATA_DISABLED: true
       BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
+      BUILD_PHASE: post-merge
       CI_BRANCH: main
       CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
       CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
@@ -513,6 +515,7 @@ jobs:
       AWS_ACCOUNT_TESSELL_PROD: ${{vars.AWS_ACCOUNT_TESSELL_PROD}}
       BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
       BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
+      BUILD_PHASE: post-merge
       CI_BRANCH: main
       CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
       CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
@@ -987,28 +990,56 @@ jobs:
               return
             fi
             git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
-            version=$(yq '.version' convoy.yaml)
-            language=$(yq '.language' convoy.yaml)
+            version=$(yq '.version // ""' convoy.yaml)
+            language=$(yq '.language // ""' convoy.yaml)
             environments=("dev" "qa" "stage" "prod")
             if [[ "$language" == "terraform" ]]; then
               terraformBuildAndPush
               return
             fi
-            yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @csv" convoy.yaml | sed 's/,/ /g' > artifacts.txt
+            yq e ".generates.$type[] | [.name, .buildAndPushFunction, .buildFunction, .buildTool, .extension, .dockerFile] | @csv" convoy.yaml | sed 's/null//g' > artifacts.txt
             lineNumber=1
             while :; do
               echo ------------------------------
-              artifactData=$(sed "$lineNumber!d" artifacts.txt)
-              if [[ -z "$artifactData" ]]; then
+              artifactData=$(sed "${lineNumber}!d" artifacts.txt)
+              if [[ -z "${artifactData}" ]]; then
                 break
               fi
-              read -r name buildFunction ext file <<< "$artifactData"
-              echo "Name: $name"
-              echo "buildFunction: $buildFunction"
-              echo "Ext: $ext"
-              echo "Version: $version"
-              echo "dockerFile: $file"
-              "${buildFunction}AndPush" $name $ext $version $file 
+
+              set -x
+              java_version=$(yq '.javaVersion // ""' convoy.yaml)
+              if [[ -n ${java_version:-} ]]; then
+                if [[ -d /usr/lib/jvm/java-${java_version}-openjdk-amd64 ]]; then
+                  export JAVA_HOME=/usr/lib/jvm/java-${java_version}-openjdk-amd64
+                else
+                  echo "Java Version ${java_version}, as required in convoy.yaml, is not installed"
+                  exit 1
+                fi
+              fi
+
+              IFS=',' read -r name buildAndPushFunction buildFunction buildTool ext file <<< "${artifactData}"
+              export ARTIFACT_NAME=${name} ARTIFACT_EXTENSION=${ext} ARTIFACT_VERSION=${version} DOCKERFILE_PATH=${file}
+              echo "Name: ${name}"
+              echo "buildAndPushFunction: ${buildAndPushFunction}"
+              echo "buildFunction: ${buildFunction}"
+              echo "buildTool: ${buildTool}"
+              echo "Ext: ${ext}"
+              echo "Version: ${version}"
+              echo "dockerFile: ${file}"
+
+              if [[ -n ${buildAndPushFunction:-} && ${buildAndPushFunction} != null ]]; then
+                set -e
+                ${buildAndPushFunction}
+                set +e
+              elif [[ -n ${buildFunction} ]]; then
+                ${buildFunction}AndPush ${name} ${ext} ${version} ${file}
+              elif [[ -n ${buildTool:-} && ${buildTool} != null ]]; then
+                set -e
+                $(yq .post-merge.${buildTool} ./ci-scripts/bash/build-tool-cmd-map.yaml)
+                set +e
+              fi
+              set +x
+
               echo "$type $name done"
               echo ------------------------------
               lineNumber=$((lineNumber+1))
@@ -1062,6 +1093,7 @@ jobs:
       ARTIFACTS_UPLOAD_ACCESS_KEY: ${{ secrets.ARTIFACTS_UPLOAD_ACCESS_KEY }}
       ARTIFACTS_UPLOAD_SECRET_KEY: ${{ secrets.ARTIFACTS_UPLOAD_SECRET_KEY }}
       BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
+      BUILD_PHASE: post-merge
       CI_BRANCH: main
       CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
       DEV_BUILD: ${{inputs.dev_build}}
diff --git a/.github/workflows/master_build_pr.yml b/.github/workflows/master_build_pr.yml
--- a/.github/workflows/master_build_pr.yml
+++ b/.github/workflows/master_build_pr.yml
@@ -14,6 +14,7 @@ jobs:
     if: ${{ inputs.type == 'ui-build' }}
     runs-on: ui-build
     env:
+      BUILD_PHASE: pre-merge
       CI_BRANCH: main
       CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
       CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
@@ -95,6 +96,7 @@ jobs:
     if: ${{ inputs.type == 'ubuntu-latest' }}
     runs-on: ubuntu-latest
     env:
+      BUILD_PHASE: pre-merge
       CI_BRANCH: main
       CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
       CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
@@ -308,6 +310,7 @@ jobs:
       ARTIFACTS_UPLOAD_SECRET_KEY: ${{ secrets.ARTIFACTS_UPLOAD_SECRET_KEY }}
       AWS_ACCOUNT_TESSELL_COMMON_INFRA: ${{vars.AWS_ACCOUNT_TESSELL_COMMON_INFRA}}
       BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
+      BUILD_PHASE: pre-merge
       CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
       CI_BRANCH: main
       CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
@@ -690,27 +693,52 @@ jobs:
               return
             fi
             git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
-            version=$(yq '.version' convoy.yaml)
-            language=$(yq '.language' convoy.yaml)
+            version=$(yq '.version // ""' convoy.yaml)
+            language=$(yq '.language // ""' convoy.yaml)
             if [[ "$language" == "terraform" ]]; then
               terraformBuild
               return
             fi
-            yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @csv" convoy.yaml | sed 's/,/ /g' > artifacts.txt
+            yq e ".generates.$type[] | [.name, .buildFunction, .buildTool, .extension, .dockerFile] | @csv" convoy.yaml | sed 's/null//g' > artifacts.txt
             lineNumber=1
             while :; do
               echo ------------------------------
-              artifactData=$(sed "$lineNumber!d" artifacts.txt)
-              if [[ -z "$artifactData" ]]; then
+              artifactData=$(sed "${lineNumber}!d" artifacts.txt)
+              if [[ -z "${artifactData}" ]]; then
                 break
               fi
-              read -r name buildFunction ext file <<< "$artifactData"
-              echo "Name: $name"
-              echo "buildFunction: $buildFunction"
-              echo "Ext: $ext"
-              echo "Version: $version"
-              echo "dockerFile: $file"
-              $buildFunction $name $ext $version $file 
+
+              set -x
+              java_version=$(yq '.javaVersion // ""' convoy.yaml)
+              if [[ -n ${java_version:-} ]]; then
+                if [[ -d /usr/lib/jvm/java-${java_version}-openjdk-amd64 ]]; then
+                  export JAVA_HOME=/usr/lib/jvm/java-${java_version}-openjdk-amd64
+                else
+                  echo "Java Version ${java_version}, as required in convoy.yaml, is not installed"
+                  exit 1
+                fi
+              fi
+
+              IFS=',' read -r name buildFunction buildTool ext file <<< "${artifactData}"
+              export ARTIFACT_NAME=${name} ARTIFACT_EXTENSION=${ext} ARTIFACT_VERSION=${version} DOCKERFILE_PATH=${file}
+              echo "Name: ${name}"
+              echo "buildFunction: ${buildFunction}"
+              echo "buildTool: ${buildTool}"
+              echo "Ext: ${ext}"
+              echo "Version: ${version}"
+              echo "dockerFile: ${file}"
+
+              if [[ -n ${buildFunction:-} && ${buildFunction} != null ]]; then
+                set -e
+                ${buildFunction} ${name} ${ext} ${version} ${file}
+                set +e
+              elif [[ -n ${buildTool:-} && ${buildTool} != null ]]; then
+                set -e
+                $(yq .pre-merge.${buildTool} ./ci-scripts/bash/build-tool-cmd-map.yaml)
+                set +e
+              fi
+              set +x
+
               echo "$type $name done"
               echo ------------------------------
               lineNumber=$((lineNumber+1))
@@ -719,6 +747,7 @@ jobs:
           }
           set +e
           source ./ci-scripts/bash/functions-for-build
+          [[ -n ${LATEST_TAG:-} ]] || export LATEST_TAG=0.0.0
           configureGoVersion
           build "artifacts"
           build "dockerImages"
@@ -739,6 +768,7 @@ jobs:
     if: ${{ inputs.type == 'arm' }}
     runs-on: ARM64
     env:
+      BUILD_PHASE: pre-merge
       CI_BRANCH: main
       CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
       CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
