TDEVOPS-2780 | Add support for go version management

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -161,6 +161,28 @@ create_tf_backend() {
 EOL
 }
 
+determine_go_version() {
+  go_version=$(yq e '.goVersion // ""' convoy.yaml)
+  if [[ -n "${go_version}" ]]; then
+    echo "Go version declared in convoy.yaml: ${go_version}"
+  else
+    runner=$(yq e '.runner // ""' convoy.yaml)
+    case "${runner}" in
+      amd) go_version="go1.19.5" ;;
+      amd-go-20) go_version="go1.20.1" ;;
+      amd-go-21) go_version="go1.21.5" ;;
+      amd-go-22) go_version="go1.22.6" ;;
+      *) 
+        echo "Error: Unknown runner value '${runner}'!"
+        exit 1
+        ;;
+    esac
+    echo "No explicit declaration of go version using ${go_version} based on runner conifg." 
+  fi
+  gvm install ${go_version}
+  gvm use ${go_version}
+}
+
 docker_build() {
   set -e
   IMAGE="${1}"
@@ -349,6 +371,48 @@ go_docker_build_and_push() {
   docker tag ${IMAGE}:latest ${DOCKERHUB_ORG}/${IMAGE}:${LATEST_TAG}
   docker push ${DOCKERHUB_ORG}/${IMAGE}:${LATEST_TAG}
   check_flyway ${IMAGE}
+  set +e
+}
+
+go_library_build() {
+  set -e
+  ARTIFACT="${1}"
+  required_inputs="1"
+  validate_inputs "${required_inputs}" "$@" 
+  NAME=$(echo "${ARTIFACT}" | awk -F '-linux' '{print $1}')
+  if [ "${NAME}" == "${ARTIFACT}" ]; then
+      NAME=$(echo "${ARTIFACT}" | awk -F '-windows' '{print $1}')
+      OS="windows"
+  else
+      OS="linux"
+  fi
+  ENGINE=$(echo "${ARTIFACT}" | awk -F "${NAME}-${OS}" '{gsub(/^-|-linux|-windows$/, "", $2); print $2}')
+  echo "Name: ${NAME}, OS: ${OS}, Engine: ${ENGINE}"
+  if [[ "${ENGINE}" == "null" || -z "${ENGINE}" ]]; then
+    make service os=${OS}
+  else
+    make service os=${OS} engine=${ENGINE}
+  fi
+  set +e
+}
+
+go_library_build_and_push() {
+  go_library_build "$@"
+  set -e
+  ARTIFACT="${1}"
+  EXTENSION="${2}"
+  mvn_deploy "${ARTIFACT}" "${EXTENSION}" "${ARTIFACT}.${EXTENSION}" "tessell.${NAME}" "${LATEST_TAG}"
+  aws_configure_prod_assets
+  aws s3 cp "${ARTIFACT}.${EXTENSION}" s3://${TESSELL_ARTIFACTS_PROD_ASSETS_S3}/terls/tessell/${NAME}/${LATEST_TAG}/
+  if ! ${DEV_BUILD}; then
+    aws s3 cp "${ARTIFACT}.${EXTENSION}" s3://${TESSELL_ARTIFACTS_PROD_ASSETS_S3}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION}
+    push_to_nexus "${ARTIFACT}.${EXTENSION}" "${NEXUS_ARTIFACT_REPO}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION}"
+    for env in "${environments[@]}"
+    do
+      push_to_minio "${ARTIFACT}.${EXTENSION}" "minio-ci/tessell-artifacts-${env}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION}"
+    done
+    generate_checksum "${ARTIFACT}.${EXTENSION}"
+  fi
   set +e
 }
 
@@ -888,6 +952,29 @@ software_def_build_and_push() {
   push_to_nexus "./common_manifest.json" "${NEXUS_ARTIFACT_REPO}/${LABEL}/delta-image-manifest/delta-image-manifest-${LATEST_TAG}.json"
 }
 
+tailscale_build() {
+  set -e
+  export GOPROXY=direct
+  export GOSUMDB='sum.golang.org'
+  go env
+  go install tailscale.com/cmd/gitops-pusher@latest
+  export TS_API_KEY=${TS_API_KEY}
+  export TS_TAILNET=${TS_TAILNET 
+  gitops-pusher --policy-file ./policy.hujson test
+  set +e
+}
+
+tailscale_build_and_push() {
+  set -e
+  export GOPROXY=direct
+  export GOSUMDB='sum.golang.org'
+  go env
+  go install tailscale.com/cmd/gitops-pusher@latest
+  export TS_API_KEY=${TS_API_KEY}
+  export TS_TAILNET=${TS_TAILNET}
+  gitops-pusher --policy-file ./policy.hujson apply
+  set +e
+}
 
 terraform_apply() {
   set -e
