Configure function configure_go_version_if_required
Additionally:
- Add dev-check for .goVersion and .runner in convoy.yaml for go repos

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -101,9 +101,11 @@ check_flyway() {
   fi
 }
 
-configure_go_version() {
-  required_go_version=$(get_required_go_version)
+configure_go_version_if_required() {
+  check_convoy_yaml
+  required_go_version=$(yq e '.goVersion // ""' convoy.yaml 2>/dev/null)
   [[ -n ${required_go_version:-} ]] || return
+  echo "Go version declared in convoy.yaml: ${required_go_version}" >&2
   if ! is_go_version_installed ${required_go_version}; then
     echo "Go lang version ${required_go_version} is not installed."
     gvm install ${required_go_version}
@@ -453,30 +455,6 @@ get_previous_commited_software_manifest() {
   echo "starting previous manifest download ${minio_path}"
   download_path="${WORKDIR}/software_image_manifest.json"
   mc cp "minio-ci/tessell-artifacts-dev/${minio_path}" "${download_path}"
-}
-
-get_required_go_version() {
-  check_convoy_yaml
-  required_go_version=$(yq e '.goVersion // ""' convoy.yaml 2>/dev/null)
-  if [[ -n ${required_go_version} ]]; then
-    echo "Go version declared in convoy.yaml: ${required_go_version}" >&2
-  # elif [[ -n ${GOROOT:-} ]]; then
-  #   echo "GOROOT is already set and convoy.yaml doesn't have 'goVersion' declared" >&2
-  else
-    runner=$(yq e '.runner // ""' convoy.yaml)
-    case "$runner" in
-      amd) required_go_version="1.19.5" ;;
-      amd-go-20) required_go_version="1.20.1" ;;
-      amd-go-21) required_go_version="1.21.5" ;;
-      amd-go-22) required_go_version="1.22.7" ;;
-      *) 
-        echo "Error: Unknown runner value '${runner}'!" >&2
-        exit 1
-        ;;
-    esac
-  fi
-  echo ${required_go_version}
-  return 0
 }
 
 go_docker_build() {
