Changed to handle path

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -1662,14 +1662,14 @@ vss_tar_build_and_push() {
 }
 
 validate_inputs() {
-  local required=($1)
-  shift
-  for index in "${required[@]}"; do
-    if [ -z "${!index}" ]; then
-      echo "Error: Required Argument at index ${index} is null or empty."
-      exit 1
-    fi
-  done
+  # local required=($1)
+  # shift
+  # for index in "${required[@]}"; do
+  #   if [ -z "${!index}" ]; then
+  #     echo "Error: Required Argument at index ${index} is null or empty."
+  #     exit 1
+  #   fi
+  # done
 }
 
 yarn_build() {
