updates

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -347,13 +347,14 @@ install_node() {
   [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
   base_node_version=$(node --version)
   node_version=$(yq eval '.nodeVersion // strenv(base_version)' convoy.yaml)
-  if nvm ls | grep -q "${node_version}"; then
-    echo "Node version ${node_version} is already installed."
+  nvm which "$node_version" > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    echo "Node version $node_version is already installed."
     nvm use ${node_version}
   else
-    echo "Node version ${node_version} not found. Installing..."
-    nvm install "${node_version}"
-    nvm use "${node_version}"
+    echo "Node version $node_version not found. Installing..."
+    nvm install "$node_version"
+    nvm use "$node_version"
   fi
 }
 
