update

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -236,6 +236,10 @@ docker_tag_and_push() {
 download_binary_from_source() {
   CONFIG_FILE="convoy.yaml"
   TMP_DIR="/tmp"
+  if yq eval '.externalUrls' ${CONFIG_FILE} &> /dev/null; then
+    echo "Please Switch to datasources for downloading binaries in terraform module. Failing build."
+    exit 1
+  fi
   if yq eval '.dataSources' "${CONFIG_FILE}" &> /dev/null; then
     echo "dataSources found in ${CONFIG_FILE}. Processing artifacts."
     data_sources=$(yq eval -o=json '.dataSources' "${CONFIG_FILE}" | jq -c '.[]')
