TDEVOPS-2709 | Add retry in image scan for trivy db download failure (#383)
* TDEVOPS-2709 | Add retry in image scan for trivy db download failure

* debug

* test

* tested

* tested

* update

* test

* updates

* test

* debug

* updates

* tested

* update

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -310,7 +310,7 @@ go_docker_build() {
   export PATH=${PATH}:${GOPATH}/bin
   git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
   ./setup -g -i
-  imageScan ${IMAGE}
+  image_scan ${IMAGE}
   set +e
 }
 
@@ -397,7 +397,26 @@ gradlew_ui_build_and_push() {
 image_scan(){
   set -e
   export IMAGE="${1}"
-  trivy image -f json -o trivy_image_scan_result.json  --severity HIGH,CRITICAL --scanners vuln $IMAGE:latest
+  RETRIES=5
+  for ((i=1; i<=RETRIES; i++)); do
+    output=$(trivy image -f json -o trivy_image_scan_result.json --severity HIGH,CRITICAL --scanners vuln ${IMAGE}:latest 2>&1 || true)
+    exit_code=$?
+    echo ${output}
+    if echo "${output}" | grep -q "TOOMANYREQUESTS"; then
+        echo "Encountered TOOMANYREQUESTS error. Retrying."
+        sleep 60
+    elif [ ${exit_code} -eq 0 ]; then
+        echo "Trivy scan completed successfully."
+        break
+    else
+        echo "Trivy scan failed with exit code ${exit_code}: ${output}"
+        exit 1
+    fi
+  done
+  if [ ${i} -gt ${RETRIES} ]; then
+    echo "Trivy scan failed after ${RETRIES} attempts."
+    exit 1
+  fi
   dockle -f json -o dockle_image_scan_result.json ${IMAGE}:latest
   python3 ./ci-scripts/python/image_scan.py
   set +e
