TDEVOPS-2609 | Add support for multiple node versions (#357)
* TDEVOPS-2609 | Add support for multiple node versions

* testing

* update runner

* updates

* test

* updates

* update

* testing

* debug

* updates

* updates

* test

* updates

* debug

* update

* updates

* updates

* update

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -348,6 +348,7 @@ gradlew_docker_tag() {
 
 gradlew_ui_build() {
   configure_npmrc_yarnrc
+  install_node
   set -e
   ENV_JSON=${TESSELL_UI_ENV_SECRET}
   echo $ENV_JSON | jq -r 'to_entries | .[] | "\(.key)=\"\(.value)\"" ' | sed '1s/^/\n/' >> .env
@@ -416,6 +417,23 @@ install_go_dependencies() {
   go version
   go install golang.org/x/tools/cmd/goimports@v0.24.0
   which go
+}
+
+install_node() {
+  export NVM_DIR="$HOME/.nvm"
+  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+  base_node_version=$(node --version)
+  export base_node_version
+  node_version=$(yq eval '.nodeVersion // strenv(base_node_version)' convoy.yaml)
+  nvm which "$node_version" > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    echo "Node version $node_version is already installed."
+  else
+    echo "Node version $node_version not found. Installing..."
+    nvm install "$node_version"
+  fi
+  nvm use ${node_version}
 }
 
 install_python_dependencies() {
@@ -489,6 +507,7 @@ mvnw_build_and_push() {
 }
 
 npm_build() {
+  install_node
   set -e
   npm install
   npm run build
@@ -504,6 +523,7 @@ npm_build() {
 }
 
 npm_build_and_push() {
+  install_node
   set -e
   npm install
   npm run build
