TDEVOPS-3960 | Add packer file in ci-scripts and build function for windows artifact (#534)

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -21,22 +21,26 @@ assert_root_pr_commit_success() {
   fi
 }
 
+aws_configure_profile() {
+  local PROFILE_NAME=$1
+  local AWS_ACCESS_KEY=$2
+  local AWS_SECRET_KEY=$3
+  local REGION=${4:-ap-south-1}
+  aws configure set aws_access_key_id ${AWS_ACCESS_KEY} --profile ${PROFILE_NAME}
+  aws configure set aws_secret_access_key ${AWS_SECRET_KEY} --profile ${PROFILE_NAME}
+  aws configure set region ${REGION} --profile ${PROFILE_NAME}
+}
+
 aws_configure_devqa_infra() {
-  aws configure set aws_access_key_id ${DEVQA_INFRA_ACCESS_KEY}
-  aws configure set aws_secret_access_key ${DEVQA_INFRA_SECRET_KEY}
-  aws configure set region ap-south-1
+  aws_configure_profile "devqa" "${DEVQA_INFRA_ACCESS_KEY}" "${DEVQA_INFRA_SECRET_KEY}"
 }
 
 aws_configure_prod_assets() {
-  aws configure set aws_access_key_id ${PROD_ASSET_ACCESS_KEY}
-  aws configure set aws_secret_access_key ${PROD_ASSET_SECRET_KEY}
-  aws configure set region ap-south-1
+  aws_configure_profile "prod" "${PROD_ASSET_ACCESS_KEY}" "${PROD_ASSET_SECRET_KEY}"
 }
 
 aws_configure_tessellops_artifacts() {
-  aws configure set aws_access_key_id ${TESSELLOPS_ARTIFACTS_DEV_ACCESS_KEY}
-  aws configure set aws_secret_access_key ${TESSELLOPS_ARTIFACTS_DEV_SECRET_KEY}
-  aws configure set region ap-south-1
+  aws_configure_profile "tessellops" "${TESSELLOPS_ARTIFACTS_DEV_ACCESS_KEY}" "${TESSELLOPS_ARTIFACTS_DEV_SECRET_KEY}"
 }
 
 bash_build() {
@@ -83,6 +87,34 @@ build_convoy_tessell_image_and_push() {
   IMAGE="${1}"
   build_convoy_tessell_image  "$@"
   docker_tag_and_push "${IMAGE}" "${LATEST_TAG}"
+}
+
+build_windows_native_artifact() {
+  set -e
+  OUTPUT="output.zip"
+  ARTIFACT="${1}"
+  EXTENSION="${2}"
+  check_convoy_yaml
+  create_powershell_env_vars
+  generate_sts_session_token ${AWS_ACCOUNT_TESSELL_DEVOPS} "ec2-full-access-role-for-convoy"
+
+  zip -r repo.zip . -x "target/*"
+  packer build ci-scripts/windows-native-builder.pkr.hcl
+  if [ ! -f "${OUTPUT}" ] || [ ! -s "${OUTPUT}" ]; then
+    echo "❌ Build failure: ${OUTPUT} is missing or empty"
+    exit 1
+  fi
+  unzip ${OUTPUT}
+  set +e
+}
+
+build_windows_native_artifact_and_push() {
+  build_windows_native_binary "$@"
+  
+  if [[ ${APP_GROUP} == ${TESSELL_GCP_APP_NAME} ]]; then
+    push_to_gcloud "${ARTIFACT}.${EXTENSION}" "gs://${TESSELL_GCP_ARTIFACTS_BUCKET}/${LABEL}/${ARTIFACT}/${ARTIFACT}.${EXTENSION}-${LATEST_TAG}"
+  fi
+  generate_checksum ${ARTIFACT}.${EXTENSION}
 }
 
 check_convoy_yaml() {
@@ -189,7 +221,7 @@ convoy_build_and_push() {
     aws_configure_tessellops_artifacts
     push_to_nexus "./build/${ARTIFACT}.${EXTENSION}" "${NEXUS_REPO_TESSELLOPS_ARTIFACTS}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION}"
     mv ./build/${ARTIFACT}.${EXTENSION}  ${ARTIFACT}.${EXTENSION}
-    aws s3 cp ${ARTIFACT}.${EXTENSION} s3://${TESSELLOPS_ARTIFACTS_DEV_S3}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION} 
+    aws s3 cp ${ARTIFACT}.${EXTENSION} s3://${TESSELLOPS_ARTIFACTS_DEV_S3}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION} --profile tessellops
 
   elif [[ ${APP_GROUP} == ${TESSELL_APP_NAME} ]]; then
     mv ./build/${ARTIFACT}.${EXTENSION}  ${ARTIFACT}.${EXTENSION}
@@ -232,6 +264,17 @@ convoy_go_library_build() {
   set -e
   go build ./...
   set +e
+}
+
+create_powershell_env_vars() {
+  OUTPUT_ENV_FILE="envvars.ps1"
+  VARS=(GITHUB_USER GITHUB_TOKEN ARTIFACT EXTENSION)
+
+  echo "" > "$OUTPUT_ENV_FILE"
+  for var in "${VARS[@]}"; do
+    val="${!var:-}"; val="${val//\"/\\\`\"}"
+    echo "\$env:$var = \"$val\"" >> "$OUTPUT_ENV_FILE"
+  done
 }
 
 create_tf_backend() {
@@ -475,10 +518,9 @@ generate_checksum() {
 
 generate_sts_session_token() {
   BUCKET_ACCOUNT=${1}
+  ROLE_NAME=${2:-"artifacts-bucket-update-role"}
   unset AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY 
-  export AWS_ACCESS_KEY_ID=${ARTIFACTS_UPLOAD_ACCESS_KEY}
-  export AWS_SECRET_ACCESS_KEY=${ARTIFACTS_UPLOAD_SECRET_KEY}
-  ROLE_ARN=arn:aws:iam::${BUCKET_ACCOUNT}:role/artifacts-bucket-update-role
+  ROLE_ARN=arn:aws:iam::${BUCKET_ACCOUNT}:role/${ROLE_NAME}
   ROLE_OUTPUT=$(aws sts assume-role --role-arn ${ROLE_ARN} --role-session-name session)
   export AWS_ACCESS_KEY_ID=$(echo ${ROLE_OUTPUT} | jq -r '.Credentials.AccessKeyId')
   export AWS_SECRET_ACCESS_KEY=$(echo ${ROLE_OUTPUT} | jq -r '.Credentials.SecretAccessKey')
@@ -819,7 +861,7 @@ mvnw_build_and_push() {
     aws_configure_tessellops_artifacts
     push_to_nexus "./target/function.zip" "${NEXUS_REPO_TESSELLOPS_ARTIFACTS}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.zip"
     mv ./target/function.zip  ${ARTIFACT}-${LATEST_TAG}.zip
-    aws s3 cp ${ARTIFACT}-${LATEST_TAG}.zip s3://${TESSELLOPS_ARTIFACTS_DEV_S3}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.zip   
+    aws s3 cp ${ARTIFACT}-${LATEST_TAG}.zip s3://${TESSELLOPS_ARTIFACTS_DEV_S3}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.zip --profile tessellops
     generate_checksum $ARTIFACT "${ARTIFACT}-${LATEST_TAG}.zip"
   fi
   set +e
@@ -1027,7 +1069,7 @@ push_release_manifest_artifacts() {
   upload_artifact ${source_file_path} ${artifact_dest_path} ${push_to}
 
   if ! ${DEV_BUILD}; then
-    aws_configure_prod_assets && aws s3 cp "${source_file_path}" s3://${TESSELLTOOLS_S3}/${artifact_dest_path}
+    aws_configure_prod_assets && aws s3 cp "${source_file_path}" s3://${TESSELLTOOLS_S3}/${artifact_dest_path} --profile prod
     
     if [[ ${release} -le 134 ]]; then
       for ENV in "${environments[@]}"
