Add assert_root_pr_commit_success and assert_base_branch_commit_success

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -2,6 +2,22 @@
 
 source ./ci-scripts/bash/functions-for-build-camel-case
 
+assert_base_branch_commit_success() {
+  base_branch_commit=$(git log origin/${SOURCE_BRANCH} -n 1 --format="%h")
+  get_commit_build_status "${base_branch_commit}" "${GITHUB_BASE_REF}"
+  if [[ "${COMMIT_BUILD_STATUS}" != "SUCCESSFUL" ]]; then
+    echo "Base branch commit ${base_branch_commit} build status is ${COMMIT_BUILD_STATUS}.\nPlease check and re-trigger the pipeline."
+    exit 1
+  fi
+}
+
+assert_root_pr_commit_success() {
+  get_commit_build_status "${base_branch_commit_of_root_pr}" "${base_branch_of_root_pr}"
+  if [[ "${COMMIT_BUILD_STATUS}" != "SUCCESSFUL" ]]; then
+    echo "Root PR commit ${base_branch_commit_of_root_pr} build status is ${COMMIT_BUILD_STATUS}.\nPlease check and re-trigger the pipeline."
+    exit 1
+  fi
+}
 aws_configure_devqa_infra() {
   aws configure set aws_access_key_id ${DEVQA_INFRA_ACCESS_KEY}
   aws configure set aws_secret_access_key ${DEVQA_INFRA_SECRET_KEY}
@@ -346,7 +362,7 @@ get_base_branch_commit_from_pr_number() {
   -H "Accept: application/vnd.github+json" \
   -H "Authorization: Bearer ${GITHUB_TOKEN}" \
   -H "X-GitHub-Api-Version: 2022-11-28" \
-  "${GH_API_URL}/repos/${REPOSITORY}/pulls/${root_pr_number}"| jq -r '.merge_commit_sha')
+  "${GH_API_URL}/repos/${REPO}/pulls/${root_pr_number}"| jq -r '.merge_commit_sha')
 }
 
 get_dc_messages() {
@@ -354,7 +370,7 @@ get_dc_messages() {
   -H "Accept: application/vnd.github+json" \
   -H "Authorization: Bearer ${GITHUB_TOKEN}" \
   -H "X-GitHub-Api-Version: 2022-11-28" \
-  "${GH_API_URL}/repos/${REPOSITORY}/pulls/${PR_NUMBER}/commits"| jq -r '.[0].commit.message' | head -n 1)
+  "${GH_API_URL}/repos/${REPO}/pulls/${PR_NUMBER}/commits"| jq -r '.[0].commit.message' | head -n 1)
 }
 
 get_root_pr_tag() {
@@ -366,6 +382,21 @@ get_root_pr_tag() {
   git diff ${base_branch_commit_of_root_pr}^!
   root_pr_tag=$(git tag --contains ${base_branch_commit_of_root_pr} | head -n 1)
   base_branch_of_root_pr="rel-$(echo "${root_pr_tag}" | cut -d. -f1,2).0"
+}
+
+get_commit_build_status() {
+  check_convoy_yaml
+  commit_hash="${1}"
+  base_branch="${2}"
+  app_group=$(yq '.appGroup' convoy.yaml)
+  
+  response=$(curl --location --request GET "${COMMIT_STATUS_API_URL}/app-groups/${app_group}/commit-hash/${commit_hash}/base-branch/${base_branch}" \
+    --header 'Content-Type: application/json' \
+    --header "x-api-key: ${CONVOY_API_KEY}" \
+    --data '')
+  validate_reponse_code ${response} "200"
+  COMMIT_BUILD_STATUS=$(echo ${response} | jq -r '.response.buildStatus')
+  echo "build_status" ${COMMIT_BUILD_STATUS}
 }
 
 get_dc_root_pr_diff() {
@@ -968,6 +999,19 @@ push_to_minio() {
   return 1
 }
 
+validate_reponse_code() {
+  RESPONSE="${1}"
+  EXPECTED_CODE="${2}"
+  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1) 
+  echo ${HTTP_CODE}
+  HTTP_CODE=$((HTTP_CODE))
+  if [ "${HTTP_CODE}" -ne 201 ]; then
+    echo "Error: Unexpected HTTP response code ${HTTP_CODE}"
+    exit 1
+  fi
+
+}
+
 push_to_nexus() {
   FILE_PATH="${1}"
   URL_PATH="${2}"
@@ -977,13 +1021,14 @@ push_to_nexus() {
       --upload-file ${FILE_PATH}  -w "%{http_code}" \
       ${NEXUS_PROTOCOL}://${NEXUS_SERVER_ENDPOINT}/repository/${URL_PATH})
   echo ${REPONSE}
-  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1) 
-  echo ${HTTP_CODE}
-  HTTP_CODE=$((HTTP_CODE))
-  if [ "${HTTP_CODE}" -ne 201 ]; then
-    echo "Error: Unexpected HTTP response code ${HTTP_CODE}"
-    exit 1
-  fi
+  validate_reponse_code "${RESPONSE}" "201"
+  # HTTP_CODE=$(echo "${RESPONSE}" | tail -n1) 
+  # echo ${HTTP_CODE}
+  # HTTP_CODE=$((HTTP_CODE))
+  # if [ "${HTTP_CODE}" -ne 201 ]; then
+  #   echo "Error: Unexpected HTTP response code ${HTTP_CODE}"
+  #   exit 1
+  # fi
 }
 
 python_docker_build_and_push() {
@@ -1089,9 +1134,11 @@ software_def_build() {
   setup_packer_env
   export CURRENT_VERSION_TAG="0.0.0"
   mkdir -p ~/.packer.d/plugins
+  assert_base_branch_commit_success
   if [[ "$BRANCH_NAME" == *double_commit* ]]; then
     echo "${BRANCH_NAME} contains double_commit"
     get_dc_root_pr_diff
+    assert_root_pr_commit_success
     git diff origin/${GITHUB_BASE_REF} --compact-summary  > ../current_pr_diff
     cat ../current_pr_diff
     if [[ ! $(diff ../root_pr_diff ../current_pr_diff) ]]; then
