updates

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -106,16 +106,6 @@ install_go_dependencies() {
   which go
 }
 
-python_docker_build_and_push() {
-  set -e
-  IMAGE="$1"
-  required_inputs="1"
-  validate_inputs "$required_inputs" "$@"
-  gradlew_docker_tag
-  docker push ${DOCKERHUB_ORG}/$IMAGE:${LATEST_TAG}
-  set +e
-}
-
 mvn_deploy() {
   ARTIFACT_ID="${1}"
   EXTENSION="${2}"
@@ -146,6 +136,34 @@ ops_ui_build_and_push() {
   set +e
 }
 
+push_to_nexus() {
+  FILE_PATH="${1}"
+  URL_PATH="${2}"
+  required_inputs="1 2"
+  validate_inputs "${required_inputs}" "$@" 
+  RESPONSE=$(curl -v -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} \
+      --upload-file ${FILE_PATH}  -w "%{http_code}" \
+      ${NEXUS_PROTOCOL}://${NEXUS_SERVER_ENDPOINT}/repository/${URL_PATH})
+  echo ${REPONSE}
+  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1) 
+  echo ${HTTP_CODE}
+  HTTP_CODE=$((HTTP_CODE))
+  if [ "${HTTP_CODE}" -ne 201 ]; then
+    echo "Error: Unexpected HTTP response code ${HTTP_CODE}"
+    exit 1
+  fi
+}
+
+python_docker_build_and_push() {
+  set -e
+  IMAGE="$1"
+  required_inputs="1"
+  validate_inputs "$required_inputs" "$@"
+  gradlew_docker_tag
+  docker push ${DOCKERHUB_ORG}/$IMAGE:${LATEST_TAG}
+  set +e
+}
+
 qa_build_and_push(){
   set -e
   required_inputs="1 3"
@@ -164,24 +182,6 @@ qa_build_and_push(){
     cd ..
   fi
   set +e
-}
-
-push_to_nexus() {
-  FILE_PATH="${1}"
-  URL_PATH="${2}"
-  required_inputs="1 2"
-  validate_inputs "${required_inputs}" "$@" 
-  RESPONSE=$(curl -v -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} \
-      --upload-file ${FILE_PATH}  -w "%{http_code}" \
-      ${NEXUS_PROTOCOL}://${NEXUS_SERVER_ENDPOINT}/repository/${URL_PATH})
-  echo ${REPONSE}
-  HTTP_CODE=$(echo "${RESPONSE}" | tail -n1) 
-  echo ${HTTP_CODE}
-  HTTP_CODE=$((HTTP_CODE))
-  if [ "${HTTP_CODE}" -ne 201 ]; then
-    echo "Error: Unexpected HTTP response code ${HTTP_CODE}"
-    exit 1
-  fi
 }
 
 setup_qa_env() {
