Add python env setter function

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -103,6 +103,33 @@ check_flyway() {
   fi
 }
 
+is_pyenv_entity_exists() {
+  pyenv versions --bare | grep -qx "${1}"
+}
+
+configure_python_version_if_required() {
+  check_convoy_yaml
+  required_python_version=$(yq e '.pythonVersion // ""' convoy.yaml 2>/dev/null)
+  [[ -n "${required_python_version:-}" ]] || return
+  echo "Python version declared in convoy.yaml: ${required_python_version}" >&2
+
+  if ! is_pyenv_entity_exists "${required_python_version}";  then
+    echo "Python ${required_python_version} not found. Installing..."
+    pyenv install "${required_python_version}"
+  fi
+
+  env_name="build-${required_python_version}"
+
+  if ! is_pyenv_entity_exists "${env_name}"; then
+    echo "Creating virtualenv ${env_name}..."
+    pyenv virtualenv "${required_python_version}" "${env_name}"
+  fi
+
+  pyenv activate "${env_name}"
+  echo "Activated pyenv environment: ${env_name}"
+  python --version
+}
+
 configure_go_version_if_required() {
   check_convoy_yaml
   required_go_version=$(yq e '.goVersion // ""' convoy.yaml 2>/dev/null)
