updates

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -84,6 +84,22 @@ check_flyway() {
   fi
 }
 
+configure_go_version() {
+  required_go_version=$(get_required_go_version)
+  if ! is_go_version_installed $required_go_version; then
+    echo "Go lang version ${required_go_version} is not installed."
+    gvm install ${required_go_version}
+  fi
+  gvm use ${required_go_version}
+  export GOROOT="/home/github/.gvm/versions/go${required_go_version}.linux.amd64"
+  export GOPATH="/home/github/.gvm/versions/go${required_go_version}"
+  export PATH="${GOROOT}/bin:${GOPATH}/bin:$PATH"
+  echo $GOROOT
+  echo $GOPATH
+  echo $PATH
+  go version
+}
+
 configure_npmrc(){
   set +e 
   REPO="${1}"
@@ -165,22 +181,6 @@ create_tf_backend() {
     }
   }
 EOL
-}
-
-configure_go_version() {
-  required_go_version=$(get_required_go_version)
-  if ! is_go_version_installed $required_go_version; then
-    echo "Go lang version ${required_go_version} is not installed."
-    gvm install ${required_go_version}
-  fi
-  gvm use ${required_go_version}
-  export GOROOT="/home/github/.gvm/versions/go${required_go_version}.linux.amd64"
-  export GOPATH="/home/github/.gvm/versions/go${required_go_version}"
-  export PATH="${GOROOT}/bin:${GOPATH}/bin:$PATH"
-  echo $GOROOT
-  echo $GOPATH
-  echo $PATH
-  go version
 }
 
 docker_build() {
@@ -399,6 +399,48 @@ go_docker_build_and_push() {
   set +e
 }
 
+go_library_build() {
+  set -e
+  ARTIFACT="${1}"
+  required_inputs="1"
+  validate_inputs "${required_inputs}" "$@"
+  NAME=$(echo "${ARTIFACT}" | awk -F '-linux' '{print $1}')
+  if [ "${NAME}" == "${ARTIFACT}" ]; then
+      NAME=$(echo "${ARTIFACT}" | awk -F '-windows' '{print $1}')
+      OS="windows"
+  else
+      OS="linux"
+  fi
+  ENGINE=$(echo "${ARTIFACT}" | awk -F "${NAME}-${OS}" '{gsub(/^-|-linux|-windows$/, "", $2); print $2}')
+  echo "Name: ${NAME}, OS: ${OS}, Engine: ${ENGINE}"
+  if [[ "${ENGINE}" == "null" || -z "${ENGINE}" ]]; then
+    make service os=${OS}
+  else
+    make service os=${OS} engine=${ENGINE}
+  fi
+  set +e
+}
+
+go_library_build_and_push() {
+  go_library_build "$@"
+  set -e
+  ARTIFACT="${1}"
+  EXTENSION="${2}"
+  mvn_deploy "${ARTIFACT}" "${EXTENSION}" "${ARTIFACT}.${EXTENSION}" "tessell.${NAME}" "${LATEST_TAG}"
+  aws_configure_prod_assets
+  aws s3 cp "${ARTIFACT}.${EXTENSION}" s3://${TESSELL_ARTIFACTS_PROD_ASSETS_S3}/terls/tessell/${NAME}/${LATEST_TAG}/
+  if ! ${DEV_BUILD}; then
+    aws s3 cp "${ARTIFACT}.${EXTENSION}" s3://${TESSELL_ARTIFACTS_PROD_ASSETS_S3}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION}
+    push_to_nexus "${ARTIFACT}.${EXTENSION}" "${NEXUS_ARTIFACT_REPO}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION}"
+    for env in "${environments[@]}"
+    do
+      push_to_minio "${ARTIFACT}.${EXTENSION}" "minio-ci/tessell-artifacts-${env}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXTENSION}"
+    done
+    generate_checksum "${ARTIFACT}.${EXTENSION}"
+  fi
+  set +e
+}
+
 gradlew_build() {
   ./gradlew build --console plain \
     -Pnexus_username="${NEXUS_USERNAME}" \
@@ -513,6 +555,7 @@ install_go_dependencies() {
   go version
   go install golang.org/x/tools/cmd/goimports@v0.24.0
   which go
+  go env
 }
 
 install_node() {
@@ -964,6 +1007,29 @@ software_def_build_and_push() {
   push_to_nexus "./common_manifest.json" "${NEXUS_ARTIFACT_REPO}/${LABEL}/delta-image-manifest/delta-image-manifest-${LATEST_TAG}.json"
 }
 
+tailscale_build() {
+  set -e
+  export GOPROXY=direct
+  export GOSUMDB='sum.golang.org'
+  go env
+  go install tailscale.com/cmd/gitops-pusher@latest
+  export TS_API_KEY=${TS_API_KEY}
+  export TS_TAILNET=${TS_TAILNET}
+  gitops-pusher --policy-file ./policy.hujson test
+  set +e
+}
+
+tailscale_build_and_push() {
+  set -e
+  export GOPROXY=direct
+  export GOSUMDB='sum.golang.org'
+  go env
+  go install tailscale.com/cmd/gitops-pusher@latest
+  export TS_API_KEY=${TS_API_KEY}
+  export TS_TAILNET=${TS_TAILNET}
+  gitops-pusher --policy-file ./policy.hujson apply
+  set +e
+}
 
 terraform_apply() {
   set -e
