Changed to handle path

diff --git a/.github/ci-scripts/bash/functions-for-build b/.github/ci-scripts/bash/functions-for-build
--- a/.github/ci-scripts/bash/functions-for-build
+++ b/.github/ci-scripts/bash/functions-for-build
@@ -1177,6 +1177,11 @@ pnpm_build() {
   required_inputs="1 2 3 4"
   set -e
   validate_inputs "${required_inputs}" "$@" 
+  DIR=$(yq eval ".generates.artifacts[] | select(.name == \"$ARTIFACT\") | .path" convoy.yaml)
+  if [[ -z "${DIR}" || "${DIR}" == "null" ]]; then
+    echo "❌ Error: Directory not found in convoy.yaml for artifact: ${ARTIFACT}"
+    exit 1
+  fi
   pushd ${DIR}
   create_npmrc
   corepack enable
@@ -1195,9 +1200,13 @@ pnpm_build_and_push() {
   ARTIFACT="${1}"
   EXTENSION="${2}"
   VERSION="${3}"
-  DIR="${4}"
-  required_inputs="1 2 3 4"
+  required_inputs="1 2 3"
   validate_inputs "${required_inputs}" "$@" 
+  DIR=$(yq eval ".generates.artifacts[] | select(.name == \"$ARTIFACT\") | .path" convoy.yaml)
+  if [[ -z "${DIR}" || "${DIR}" == "null" ]]; then
+    echo "❌ Error: Directory not found in convoy.yaml for artifact: ${ARTIFACT}"
+    exit 1
+  fi
   pnpm_build "$@"
   set -e
   pushd ${DIR}
