Update build_go_library.yaml

diff --git a/.github/workflows/build_go_library.yaml b/.github/workflows/build_go_library.yaml
--- a/.github/workflows/build_go_library.yaml
+++ b/.github/workflows/build_go_library.yaml
@@ -65,13 +65,109 @@ jobs:
             print(\"::set-output name=engine::\" + exporter_config[os_type])   
           """
           
-      - name: Make clinets
+      - name: Values from input
         run: |
-          echo "Building the service"
-          git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
           echo ${{ steps.values.outputs.os_type }}
           echo ${{ steps.values.outputs.exporter_name }}
           echo ${{ steps.values.outputs.engine }}
+
+      - name: make clients
+        run: |
+          declare -A os_eng
+            os_eng["linux"]=('mysql')
+            os_eng["windows"]=('mssql') 
+          echo "Building the service"
+          git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
+          for os in "${!os_eng[@]}"; do
+            engines_in_os=("${os_eng[$os]}")
+              for engine in "${engines_in_os[@]}"; do
+                make service $os $engine
+              done
+          done
+          ls
+          
+          
+      - name: Get tags
+        uses: nick-fields/retry@v2.8.1
+        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
+        with:
+          timeout_seconds: 10
+          max_attempts: 3
+          retry_on: error
+          command: |
+            git fetch --all
+            git tag --contains '${{ github.event.after }}'
+            latest_tags+=("$(git tag --contains '${{ github.event.after }}')")
+            if [[ "$latest_tags" == '' ]]; then 
+              echo " Tag is Empty"
+              exit 1
+            fi
+            echo "Tag is present: $latest_tags"       
+            for tag in $latest_tags; do tag_arr+=($tag); done
+            echo "TAGS=${tag_arr[@]}" >> $GITHUB_ENV
+            
+      - name: Find latest tag
+        uses: actions/github-script@v6.3.3
+        id: latest_tag
+        #if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
+        with:
+          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
+          script: |
+            console.log("Tags are " + "${{ env.TAGS }}")
+            latest_tag = '0.0.0'
+            // process multiple tags if any
+            tags = "${{ env.TAGS }}".split(' ')
+            if (tags.length == 1) {
+              console.log("There is only one tag. Using it." + tags[0])
+              latest_tag = tags[0]
+            } else {
+              if ("${{ env.SOURCE_BRANCH }}" == "main") {
+                for (i in tags) {
+                  tag = tags[i]
+                  console.log("Checking tag " + tag)
+                  if (latest_tag == null) {
+                    latest_tag = tag
+                    continue
+                  }
+                  latest_parts = latest_tag.split(".")
+                  tag_parts = tag.split(".")
+                  for (i = 0; i < tag_parts.length; i++) {
+                    if (parseInt(tag_parts[i]) < parseInt(latest_parts[i])) {
+                      console.log("Skipping " + tag)
+                      break
+                    }
+                    if (parseInt(tag_parts[i]) > parseInt(latest_parts[i])) {
+                      latest_tag = tag
+                      console.log("Setting " + latest_tag)
+                      break
+                    }
+                  }
+                }
+              } else {
+                tag_base = "${{ env.SOURCE_BRANCH }}".substring(4).split(".").slice(0,2)
+                latest_tag = tag_base.join(".") + ".0"
+                for (i in tags) {
+                  tag = tags[i]
+                  console.log("branch - Checking tag " + tag)
+                  tag_parts = tag.split(".")
+                  if (tag_base[0] == tag_parts[0] && tag_base[1] == tag_parts[1]) {
+                    latest_parts = latest_tag.split(".")
+                    if (parseInt(latest_parts[2]) < parseInt(tag_parts[2])) {
+                      latest_tag = tag
+                    }
+                  }
+                }
+              }
+            }
+            latest_tag = '100.0.10'
+            console.log("Latest tag: " + latest_tag)
+            // check if we have
+            if ( latest_tag == '' || latest_tag === undefined) {
+              console.log("Couldn't determine the latest tag, exiting. Retry manually..")
+              process.exit(1);
+            }
+            core.setOutput('tag_ref', latest_tag)
+            
           
           
           
