Push images for devops service (#63)
* Push images for devops service

* Fix Dockerfile and buildfile

* Fix Dockerfile and buildfile

* Fix syntax error

diff --git a/.github/workflows/build_devops.yml b/.github/workflows/build_devops.yml
--- a/.github/workflows/build_devops.yml
+++ b/.github/workflows/build_devops.yml
@@ -12,7 +12,7 @@ jobs:
   # This workflow contains a single job called "build"
   build:
     # The type of runner that the job will run on
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     outputs:
       mail_id_output: ${{ steps.mail_info.outputs.mail_id }}
       mail_subject_output: ${{ steps.mail_info.outputs.mail_subject}}
@@ -22,22 +22,36 @@ jobs:
       NEXUS_SERVER: nexus.tessell.cloud
       NEXUS_PULL_REPOS_PY: tessell-py-development
       NEXUS_PUSH_REPOS_PY: tessell-repos-py-component
+      DOCKERHUB_ORG: "tesselldev"
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.9
+
+      - name: Set up JDK 16
+        uses: actions/setup-java@v3.10.0
+        with:
+          java-version: '16'
+          distribution: 'adopt'
 
       - name: Get branch name & Repo Name
         shell: bash
         run: |
           echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
           echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -f2 -d'/')" >> $GITHUB_ENV
+          echo "DOCKER_IMAGE_NAME=$(echo ${GITHUB_REPOSITORY} | cut -f2 -d'/')" >> $GITHUB_ENV
 
       - name: Set Pull repository
         if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
         shell: bash
         run: |
           echo "NEXUS_PULL_REPOS_PY=tessell-py-component" >> $GITHUB_ENV
+          echo "DOCKERHUB_ORG=tessellprod" >> $GITHUB_ENV
 
       - name: Create pip conf
         run: |
@@ -53,6 +67,8 @@ jobs:
 
       - name: Install dependencies
         run: |
+          python3 -m pip install --upgrade pip
+          pip install flake8 pytest twine wheel
           python3 -m pip install -r ${{ env.REPO_NAME }}/requirements.txt --dry-run
 
       - name: Lint with flake8
@@ -69,12 +85,18 @@ jobs:
           export PATH=/opt/tessell/python/install/bin:$PATH
           pytest
 
+      - name: Login to docker
+        uses: docker/login-action@v2.1.0
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
 
       - name: Build Wheel
-        if: ${{ startsWith(env.SOURCE_BRANCH,'TS-') }}
+        if: ${{ !startsWith(env.SOURCE_BRANCH,'rel-') && env.SOURCE_BRANCH != 'main' }}
         run: |
           export PATH=/opt/tessell/python/install/bin:$PATH
-          ./gradlew pythonWheel --console plain \
+          ./gradlew pythonWheel docker --console plain \
             -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
             -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}"
 
@@ -83,7 +105,7 @@ jobs:
         if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
         run: |
           export PATH=/opt/tessell/python/install/bin:$PATH
-          ./gradlew twineUpload --console plain \
+          ./gradlew twineUpload dockerTag --console plain \
             -Pnexus_push_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
             -Pnexus_push_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
             -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
@@ -91,6 +113,128 @@ jobs:
             -Pnexus_push_repo_py="${{ env.NEXUS_PUSH_REPOS_PY }}" \
             -Pnexus_pull_repo_py="${{ env.NEXUS_PULL_REPOS_PY }}"
 
+      - name: getting commit id for workflow_dispatch
+        uses: actions/github-script@v6.3.3
+        id: find_commit
+        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
+        with:
+          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
+          script: |
+            if (${{ github.event_name  == 'workflow_dispatch'}} ){
+                core.setOutput('commit_id', "${{ github.sha }}" )
+            }
+            else{
+               core.setOutput('commit_id', "${{ github.event.after }}" )
+            }
+            
+      - name: Get tags
+        uses: nick-fields/retry@v2.8.1
+        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
+        with:
+          timeout_seconds: 10
+          max_attempts: 3
+          retry_on: error
+          command: |
+            git fetch --all
+            git tag --contains '${{ steps.find_commit.outputs.commit_id}}'
+            latest_tags+=("$(git tag --contains '${{ steps.find_commit.outputs.commit_id }}')")
+            if [[ "$latest_tags" == '' ]]; then 
+              echo " Tag is Empty"
+              exit 1
+            fi
+            echo "Tag is present: $latest_tags"       
+            for tag in $latest_tags; do tag_arr+=($tag); done
+            echo "TAGS=${tag_arr[@]}" >> $GITHUB_ENV
+      
+      
+      - name: Find latest tag
+        uses: actions/github-script@v6.3.3
+        id: latest_tag
+        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
+        with:
+          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
+          script: |
+            console.log("Tags are " + "${{ env.TAGS }}")
+            latest_tag = '0.0.0'
+            // process multiple tags if any
+            tags = "${{ env.TAGS }}".split(' ')
+            if (tags.length == 1) {
+              console.log("There is only one tag. Using it." + tags[0])
+              latest_tag = tags[0]
+            } else {
+              if ("${{ env.SOURCE_BRANCH }}" == "main") {
+                for (i in tags) {
+                  tag = tags[i]
+                  console.log("Checking tag " + tag)
+                  if (latest_tag == null) {
+                    latest_tag = tag
+                    continue
+                  }
+                  latest_parts = latest_tag.split(".")
+                  tag_parts = tag.split(".")
+                  for (i = 0; i < tag_parts.length; i++) {
+                    if (parseInt(tag_parts[i]) < parseInt(latest_parts[i])) {
+                      console.log("Skipping " + tag)
+                      break
+                    }
+                    if (parseInt(tag_parts[i]) > parseInt(latest_parts[i])) {
+                      latest_tag = tag
+                      console.log("Setting " + latest_tag)
+                      break
+                    }
+                  }
+                }
+              } else {
+                tag_base = "${{ env.SOURCE_BRANCH }}".substring(4).split(".").slice(0,2)
+                latest_tag = tag_base.join(".") + ".0"
+                for (i in tags) {
+                  tag = tags[i]
+                  console.log("branch - Checking tag " + tag)
+                  tag_parts = tag.split(".")
+                  if (tag_base[0] == tag_parts[0] && tag_base[1] == tag_parts[1]) {
+                    latest_parts = latest_tag.split(".")
+                    if (parseInt(latest_parts[2]) < parseInt(tag_parts[2])) {
+                      latest_tag = tag
+                    }
+                  }
+                }
+              }
+            }
+            console.log("Latest tag: " + latest_tag)
+            // check if we have
+            if ( latest_tag == '' || latest_tag === undefined) {
+              console.log("Couldn't determine the latest tag, exiting. Retry manually..")
+              process.exit(1);
+            }
+            core.setOutput('tag_ref', latest_tag)
+     
+      - name: tagging docker image with scan
+        run: |
+           docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ${{ env.DOCKER_IMAGE_NAME }}:scan
+      
+      - name: Docker image scan
+        id: docker-image-scan
+        uses: azure/container-scan@v0.1
+        with:
+            severity-threshold: CRITICAL
+            image-name: ${{ env.DOCKER_IMAGE_NAME }}:scan
+            username: ${{ secrets.DOCKER_USERNAME }}
+            password: ${{ secrets.DOCKER_PASSWORD }}
+            trivy-version: "0.29.1"
+
+      - uses: actions/upload-artifact@v3
+        with:
+            name: image-scan-report
+            path: ${{ steps.docker-image-scan.outputs.scan-report-path }}
+            
+      - name: Sign and push docker image
+        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
+        uses: sudo-bot/action-docker-sign@latest
+        with:
+          image-ref: "${{ env.DOCKERHUB_ORG }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.latest_tag.outputs.tag_ref }}"
+          private-key-id: ${{ secrets.DCT_PRIVATE_KEY_ID }}
+          private-key: ${{ secrets.DCT_PRIVATE_KEY }}
+          private-key-passphrase: ${{ secrets.DCT_PRIVATE_KEY_PASSPHRASE }}
       - name: Slack Notification
         uses: act10ns/slack@v1.5.0
         if: ${{ failure() && (startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main') }}
