added label validation

diff --git a/.github/workflows/create_tag.yml b/.github/workflows/create_tag.yml
--- a/.github/workflows/create_tag.yml
+++ b/.github/workflows/create_tag.yml
@@ -131,6 +131,45 @@ jobs:
         run: |
           echo "tag_ref=${{steps.create_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
 
+      - name: Set Label
+        shell: bash
+        run: |
+          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
+            TOKEN=$(echo -n '${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}}' | base64 -w 0)
+            APP_GROUP=$(yq '.appGroup // "tessell"' convoy.yaml)
+            URL="http://${{vars.CONVOY_DEV_API_ENDPOINT}}/devops/applications/app-groups/$APP_GROUP/latest-main-release-label"
+            RESPONSE=$(curl --location "$URL" \
+                    --header "Authorization: Basic $TOKEN")
+            echo "$RESPONSE"
+            LABEL=$(echo "$RESPONSE" | jq -r '.["latest-main-release-label"]')
+            echo "$LABEL"
+            if [ $? -eq 0 ]; then
+              if [[ $LABEL == rel* ]]; then
+                  echo "LABEL=$LABEL" >> $GITHUB_ENV
+              else
+                  echo "Response: $LABEL"
+                  echo "Label does not start with 'rel'. Check response."
+                  exit 1 
+              fi
+            else
+                echo "Failed API request."
+                exit 1
+            fi
+          else
+            echo "LABEL=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
+          fi
+
+      - name: Validate Label
+        run: |
+          tag=$(echo ${{steps.create_tag.outputs.tag_ref}} | cut -d '.' -f 2)
+          label=$(echo ${{env.LABEL}} | cut -d '.' -f 2)
+          if [ "$tag" == "$label" ]; then
+              echo "TAG and LABEL are on same release label: rel-$TAG"
+          else
+              echo "TAG and LABEL are on different release label. Please check git tag and API response."
+              exit 1
+          fi   
+
       - name: Slack Notification
         uses: act10ns/slack@v1.5.0
         with:
@@ -185,7 +224,7 @@ jobs:
 
       - name: POST API to Convoy
         env:
-          API_URL: http://convoy-devops.convoy-dev:8080/devops/git-metadata/commits
+          API_URL: http://${{vars.CONVOY_DEV_API_ENDPOINT}}/devops/git-metadata/commits
           COMMIT_HASH: "${{github.sha}}"
           REPO: "${{github.event.pull_request.base.repo.name}}"
           TAG: "${{needs.create-tag-on-merge.outputs.tag_ref_output}}"
