removed -g

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -164,23 +164,23 @@ jobs:
         run: |
           sudo sudo npm install jsonlint -g
           
-      - name: Check for Jsonlint
-        run: |
-          set -e
-          git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.json$' | xargs -I{} sh -c 'jsonlint -q "{}" || { echo "::error::Invalid JSON file: {}"; exit 1; }'
+      # - name: Check for Jsonlint
+      #   run: |
+      #     set -e
+      #     git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.json$' | xargs -I{} sh -c 'jsonlint -q "{}" || { echo "::error::Invalid JSON file: {}"; exit 1; }'
 
       - name: install octokit/rest
         run: |
           if [ ! -d "node_modules/@octokit/rest" ]; then
             npm cache clean --force
-            sudo sudo npm install @octokit/rest --legacy-peer-deps -g
+            npm install @octokit/rest --legacy-peer-deps
           fi
       - name: install node fetch 
         run: | 
-          sudo sudo npm install node-fetch -g
+          npm install node-fetch 
 
       - name: Install dependencies
-        run: sudo sudo npm install js-yaml -g
+        run: npm install js-yaml
 
       - name: Check for merge conflicts
         uses: actions/github-script@v6.4.1
