Update dev-checks.yml

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -95,6 +95,19 @@ jobs:
       - name: Check for merge conflict in PR
         run: |
           if [ $(git grep -rln '<<<<<<< HEAD' -- ':(exclude)*dev-checks.yml') ]; then echo "Please resolve the merge conflict"; exit 1; else exit 0; fi
+          
+      - name: Check for Jsonlint
+        run: |
+          for file in $(git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}); do
+            if [[ $file == *.json ]]; then
+              echo "Checking JSON file: $file"
+              jsonlint -q $file
+              if [[ $? -ne 0 ]]; then
+                echo "::error::Invalid JSON file: $file"
+                exit 1
+              fi
+            fi
+          done
 
       - name: install octokit/rest
         run: |
