TDEVOPS-488 | Format, extraction, validation checks (#94)
* Format, extraction, validation checks

* updates

* Jira types update

* update

* Updates

* build test

* version

* updates

* built changes

* updates

* updates

* changes

* updates

* updates

* seprated format and extraction

* bug

* dependencies

* updates

* updates

* updates

* updates

* updates

* quotes handling

---------

Co-authored-by: Sundeep Gupta <sundeep.gupta@tessell.com>

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -18,21 +18,6 @@ on:
         required: false
         type: string
         default: 'true'
-      check_branch_name:
-        description: 'This is used to check branch name starts with TS-'
-        required: false
-        type: string
-        default: 'true'
-      check_existing_branch_name:
-        description: 'This is used to check whether same branch is existing or no'
-        required: false
-        type: string
-        default: 'true'
-      check_valid_jira:
-        description: 'This is used to check if we are using a valid jira or not'
-        required: false
-        type: string
-        default: 'true'
       check_terraform_provider_version:
         description: 'This is used to check terraform provider version in terraform files'
         required: false
@@ -81,15 +66,71 @@ jobs:
           echo "SOURCE_BRANCH=$(echo ${{ github.event.pull_request.head.ref }} | tr / -)" >> $GITHUB_ENV
           echo "TARGET_BRANCH=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
           echo "GITHUB_TOKEN=${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}" >> $GITHUB_ENV
-        
-      - name: Check branch name
+      
+      - name: Check Format
+        env:
+          PR_TITLE: ${{ github.event.pull_request.title }}
         run: |
-         if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^(TS|TDEVOPS|TOPS|revert)-'; then
-           echo "Branch name starts with 'TS-' or 'revert-' or 'TDEVOPS-'" 
-         else
-           echo "Branch name does not start with 'TS-' or 'revert-' or 'TDEVOPS-' or 'TOPS-'"
-           exit 1
-         fi
+          if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^revert-'; then
+              echo "Revert branch, skipping Format check"
+              exit 0
+          fi
+          if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^TS-' || echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^revert-' || echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^TDEVOPS-' || "${{ env.SOURCE_BRANCH }}" | grep -Eq '^TOPS-'; then
+            echo "Branch name starts with 'TS-' or 'revert-' or 'TDEVOPS-'or 'TOPS-" 
+          else
+            echo "Branch name does not start with 'TS-' or 'revert-' or 'TDEVOPS-' or 'TOPS-'. Checking PR title format."
+            PULL_REQUEST_TITLE="$PR_TITLE"
+            PATTERN="^(TS|TDEVOPS|TOPS)-[0-9]+\s\|\s[a-zA-Z0-9]+$"
+            if [[ ! $PULL_REQUEST_TITLE =~ $PATTERN ]]; then
+              echo "Error: Pull request title is not in the required format. Please use 'TS-XXXX | --' or 'TDEVOPS-XXXX | --' or 'TOPS-XXXX | --' format."
+              exit 1
+            else 
+              echo "PR Title is in the valid format."
+            fi  
+          fi
+
+      - name: Check convoy.yaml
+        id: convoy_check
+        run: |
+          if [ -f "convoy.yaml" ]; then
+            echo "convoy_exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "convoy_exists=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install shyaml
+          echo ${{steps.convoy_check.outputs.convoy_exists}}
+            
+      - name: Extract Jira Ticket
+        if: ${{ steps.convoy_check.outputs.convoy_exists == 'true' }}
+        id: extract
+        env:
+          PR_TITLE: ${{github.event.pull_request.title}}
+        run: |
+          if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^revert-'; then
+              echo "Revert branch, skipping Jira Extraction"
+              exit 0
+          fi
+          jira_source=$(shyaml get-value ci.best-practices.jiraValidation.jiraIdSource < convoy.yaml)
+          jira_match=$(shyaml get-value ci.best-practices.jiraValidation.matchingRule < convoy.yaml)
+          extract_jira_id "${{env.SOURCE_BRANCH}}" "$PR_TITLE" "$jira_source" "$jira_match"
+
+      - name: Validate Jira Ticket
+        if: ${{ steps.convoy_check.outputs.convoy_exists == 'true' }}
+        run: |
+          if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^revert-'; then
+            echo "Revert branch, skipping Jira Validation"
+            exit 0
+          fi
+          echo "${{steps.extract.outputs.jira_ticket}}"
+          validate_jira_id '${{ secrets.JIRA_USERNAME }}' '${{ secrets.JIRA_API_TOKEN }}' '${{ steps.extract.outputs.jira_ticket }}'
+
       - name: Check double commit
         env: 
           PR_TITLE: ${{github.event.pull_request.title}}
@@ -105,6 +146,7 @@ jobs:
           else
             echo "No double commit conflicts found in Branch or PR title."
           fi
+
       - name: import packages for json lint
         run: |
           sudo sudo npm install jsonlint -g
@@ -538,10 +580,6 @@ jobs:
         run:
           terraform_version_check "${{ steps.terraform_check.outputs.terraform_file }}"
       
-      #- name: Jira number validation
-      #  run: |
-      #    jira_check '${{ secrets.JIRA_USERNAME }}' '${{ secrets.JIRA_API_TOKEN }}' '${{ env.SOURCE_BRANCH }}'
-
       - name: check to verify same branch is exist
         if: ${{ startsWith(env.TARGET_BRANCH,'rel-') && !contains(env.SOURCE_BRANCH,'double_commit') }}
         run: |
