Update dev-checks.yml

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -164,10 +164,10 @@ jobs:
         run: |
           sudo sudo npm install jsonlint -g
           
-      # - name: Check for Jsonlint
-      #   run: |
-      #     set -e
-      #     git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.json$' | xargs -I{} sh -c 'jsonlint -q "{}" || { echo "::error::Invalid JSON file: {}"; exit 1; }'
+      - name: Check for Jsonlint
+        run: |
+          set -e
+          git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.json$' | xargs -I{} sh -c 'jsonlint -q "{}" || { echo "::error::Invalid JSON file: {}"; exit 1; }'
 
       - name: install octokit/rest
         run: |
