Update dev-checks.yml

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -102,16 +102,7 @@ jobs:
           
       - name: Check for Jsonlint
         run: |
-          for file in $(git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}); do
-            if [[ $file == *.json ]]; then
-              echo "Checking JSON file: $file"
-              jsonlint -q $file
-              if [[ $? -ne 0 ]]; then
-                echo "::error::Invalid JSON file: $file"
-                exit 1
-              fi
-            fi
-          done
+          git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.json$' | xargs -I{} sh -c 'jsonlint -q "{}" || echo "::error::Invalid JSON file: {}"'
 
       - name: install octokit/rest
         run: |
