Format, extraction, validation checks

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -18,8 +18,8 @@ on:
         required: false
         type: string
         default: 'true'
-      check_branch_name:
-        description: 'This is used to check branch name starts with TS-'
+      check_branch_pr_format:
+        description: 'This is used to check branch name and PT title format'
         required: false
         type: string
         default: 'true'
@@ -28,6 +28,21 @@ on:
         required: false
         type: string
         default: 'true'
+      jira_id_source:
+        description: 'This is used to specify the Jira ID source'
+        required: true
+        type: string
+        default: 'BRANCH'
+      jira_match_type:
+        description: 'This is used to specify to check both the sources or any or none'
+        required: true
+        type: string
+        default: 'ANY'    
+      extract_valid_jira:
+        description: 'This is used to extract Jira Ticket from Branch name or PR Title'
+        required: true
+        type: string
+        default: 'true'    
       check_valid_jira:
         description: 'This is used to check if we are using a valid jira or not'
         required: false
@@ -82,16 +97,24 @@ jobs:
           echo "TARGET_BRANCH=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
           echo "GITHUB_TOKEN=${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}" >> $GITHUB_ENV
         
-      - name: Check branch name
+      - name: Check branch and PR title format
+        if: ${{ inputs.check_branch_pr_format == 'true' }}
         run: |
-         if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^TS-' || echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^revert-' || echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^TDEVOPS-'; then
-           echo "Branch name starts with 'TS-' or 'revert-' or 'TDEVOPS-'" 
-         else
-           echo "Branch name does not start with 'TS-' or 'revert-' or 'TDEVOPS-'"
-           exit 1
-         fi
+          if echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^TS-' || echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^revert-' || echo "${{ env.SOURCE_BRANCH }}" | grep -Eq '^TDEVOPS-'; then
+            echo "Branch name starts with 'TS-' or 'revert-' or 'TDEVOPS-'" 
+            exit 0
+          else
+            echo "Branch name does not start with 'TS-' or 'revert-' or 'TDEVOPS-'. Checking PR title format."
+            PULL_REQUEST_TITLE="${{ github.event.pull_request.title }}"
+            PATTERN="^(TS|TDEVOPS)-[0-9]+\s\|\s[a-zA-Z0-9]+$"
+            if [[ ! $PULL_REQUEST_TITLE =~ $PATTERN ]]; then
+              echo "Error: Pull request title is not in the required format. Please use 'TS-XXXX | --' or 'TDEVOPS-XXXX | --' format."
+              exit 1
+            else 
+              echo "PR Title is in the valid format."
+            fi  
+          fi
       
-
       - name: Check for merge conflict in PR
         run: |
           if [ $(git grep -rln '<<<<<<< HEAD' -- ':(exclude)*dev-checks.yml') ]; then echo "Please resolve the merge conflict"; exit 1; else exit 0; fi
@@ -387,9 +410,20 @@ jobs:
         run:
           terraform_version_check "${{ steps.terraform_check.outputs.terraform_file }}"
       
-      #- name: Jira number validation
-      #  run: |
-      #    jira_check '${{ secrets.JIRA_USERNAME }}' '${{ secrets.JIRA_API_TOKEN }}' '${{ env.SOURCE_BRANCH }}'
+      - name: Extract Jira Ticket
+        id: extract
+        if: ${{inputs.extract_valid_jira == 'true' && inputs.jira_match_type != 'NONE'  }}
+        run: |
+          if [inputs.jira_match_type == 'ALL']; then
+            extract_jira_id '${{env.SOURCE_BRANCH}}' '${{github.event.pull_request.title}}' '${{inputs.jira_id_source}}' '${{inputs.jira_match_type}}'
+          elif [inputs.jira_match_type == 'ANY']; then
+            extract_jira_id '${{env.SOURCE_BRANCH}}' '${{github.event.pull_request.title}}' '${{inputs.jira_id_source}}' '${{inputs.jira_match_type}}'
+
+      - name: Validate Jira Ticket
+        if: ${{inputs.check_valid_jira == 'true' &&  inputs.jira_match_type != 'NONE' }}
+        run: |
+          echo "${{steps.extract.outputs.jira_ticket}}"
+          validate_jira_id '${{ secrets.JIRA_USERNAME }}' '${{ secrets.JIRA_API_TOKEN }}' '${{ steps.extract.outputs.jira_ticket }}'
 
       - name: check to verify same branch is exist
         if: ${{ startsWith(env.TARGET_BRANCH,'rel-') && !contains(env.SOURCE_BRANCH,'double_commit') }}
