Update dev-checks.yml

diff --git a/.github/workflows/dev-checks.yml b/.github/workflows/dev-checks.yml
--- a/.github/workflows/dev-checks.yml
+++ b/.github/workflows/dev-checks.yml
@@ -105,7 +105,7 @@ jobs:
         run: |
           set -e
           git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.json$' | xargs -I{} sh -c 'jsonlint -q "{}" || { echo "::error::Invalid JSON file: {}"; exit 1; }'
-          git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.yaml$' | xargs -I{} sh -c 'yamllint -q "{}" || { echo "::error::Invalid YAML file: {}"; exit 1; }'
+          git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.yaml$' | xargs -I{} sh -c 'yamllint "{}" || { echo "::error::Invalid YAML file: {}"; exit 1; }'
 
       - name: install octokit/rest
         run: |
