TDEVOPS-3063 | Enable support for enforceK8sResourceSeparator

diff --git a/.github/workflows/master_dev_checks.yml b/.github/workflows/master_dev_checks.yml
--- a/.github/workflows/master_dev_checks.yml
+++ b/.github/workflows/master_dev_checks.yml
@@ -263,16 +263,19 @@
         - name: Check for new line at EOF
           run: |
             enforce_newline_at_eof=$(yq e '.enforceNewLineAtEOF // false' convoy.yaml)
+
             if [ "${enforce_newline_at_eof}" = "true" ]; then
               echo "Checking changed files for missing newline at EOF..."
               git checkout ${{github.base_ref}} && git pull
               git checkout ${{github.head_ref}} && git pull
+              
               missing_newline_files=()
               while IFS= read -r file; do
                 if [ -f "$file" ] && [ -n "$(tail -c 1 "$file" | tr -d '\n')" ]; then
                   missing_newline_files+=("$file")
                 fi
               done < <(git diff --name-only "${{github.base_ref}}"..."${{github.head_ref}}")
+
               if [ ${#missing_newline_files[@]} -gt 0 ]; then
                 echo "The following files are missing a newline at EOF:"
                 printf '%s\n' "${missing_newline_files[@]}"
@@ -283,6 +286,35 @@
               fi
             else
               echo "'enforceNewLineAtEOF' is set to false. Skipping newline checks."
+            fi
+        
+        - name: Check for YAML separators
+          run: |
+            enforce_k8s_separator=$(yq e '.enforceK8sResourceSeparator // false' convoy.yaml)
+
+            if [ "${enforce_k8s_separator}" = "true" ]; then
+              echo "Checking changed YAML files for missing '---' separator at the beginning."
+              git checkout ${{github.base_ref}} && git pull
+              git checkout ${{github.head_ref}} && git pull
+              
+              missing_separator_files=()
+              while IFS= read -r file; do
+                if [[ "${file}" == *.yaml || "${file}" == *.yaml.tmpl ]]; then
+                  if [ -f "${file}" ] && [ "$(head -n 1 "${file}")" != "---" ]; then
+                    missing_separator_files+=("${file}")
+                  fi
+                fi
+              done < <(git diff --name-only "${{github.base_ref}}"..."${{github.head_ref}}")
+        
+              if [ ${#missing_separator_files[@]} -gt 0 ]; then
+                echo "The following YAML files are missing a '---' separator at the beginning:"
+                printf '%s\n' "${missing_separator_files[@]}"
+                exit 1
+              else
+                echo "All modified YAML files have the required '---' separator."
+              fi
+            else
+              echo "'enforceK8sResourceSeparator' is set to false. Skipping YAML separator checks."
             fi
 
         - name: Check DB Migration Scripts
