updates

diff --git a/.github/workflows/master_find_latest_tag.yml b/.github/workflows/master_find_latest_tag.yml
--- a/.github/workflows/master_find_latest_tag.yml
+++ b/.github/workflows/master_find_latest_tag.yml
@@ -3,9 +3,11 @@ name: Find latest tag
 on:
   workflow_call:
     inputs:
-      artifact_version:
-        description: 'Version with which to push the artifact'
-        type: string
+      dev_build:
+        description: 'Determine whether dispatch is on dev branch or not'
+        required: false
+        default: false
+        type: boolean
     outputs:
       tag:
         description: "Latest tag"
@@ -37,7 +39,7 @@ jobs:
               
       - name: Get tags
         uses: nick-fields/retry@v3.0.0
-        if: ${{ inputs.artifact_version  == '' }}
+        if: ${{ inputs.dev_build }}
         with:
           timeout_seconds: 10
           max_attempts: 3
@@ -60,7 +62,7 @@ jobs:
       - name: Find latest tag
         uses: actions/github-script@v7.0.1
         id: latest_tag
-        if: ${{ inputs.artifact_version  == '' }}
+        if: ${{ inputs.dev_build }}
         with:
           github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
           script: |
@@ -121,10 +123,18 @@ jobs:
       - name: Tag Output
         id: tag_output
         run: |
-          if [ ${{inputs.artifact_version}} == '' ]; then
-            echo "tag_ref=${{steps.latest_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
+          if [ ${{inputs.dev_build}} ]; then
+            branch_name="${{github.ref_name}}"
+            if [[ "${branch_name}" =~ ^[^-]+-([0-9]+) ]]; then
+              version="0.0.${BASH_REMATCH[1]}"
+            else
+              echo "Error: Branch name is not in format 'TS/TDEVOPS/SRE-XXXX'"
+              exit 1
+            fi
+            echo "Constructed version: ${version}"
+            echo "tag_ref=${version}" >> $GITHUB_OUTPUT
           else
-            echo "tag_ref=${{inputs.artifact_version}}" >> $GITHUB_OUTPUT
+            echo "tag_ref=${{steps.latest_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
           fi
           
       - name: Slack Notification
