updates

diff --git a/.github/workflows/master_build_merge.yml b/.github/workflows/master_build_merge.yml
--- a/.github/workflows/master_build_merge.yml
+++ b/.github/workflows/master_build_merge.yml
@@ -71,6 +71,7 @@ jobs:
             cat ~/.npmrc
           }
           configureNpmrcYarnrc() {
+            set +e
             rm ~/.npmrc
             rm ~/.yarnrc
             TOKEN=$(echo -n '${{env.NEXUS_USERNAME}}:${{env.NEXUS_PASSWORD}}' | base64 -w 0)
@@ -113,8 +114,8 @@ jobs:
             set +e
           }
           gradlewUIBuild() {
-            set -e
             configureNpmrcYarnrc
+            set -e
             ENV_JSON='${{secrets.TESSELL_UI_ENV_SECRET}}'
             echo "$ENV_JSON" | jq -r 'to_entries | .[] | "\(.key)=\"\(.value)\"" ' | sed '1s/^/\n/' >> .env
             cat .env
@@ -225,13 +226,13 @@ jobs:
           build "helmCharts"
           echo "ARTIFACT_CHECKSUMS=$ARTIFACT_CHECKSUMS" >> $GITHUB_OUTPUT
 
-      - name: Slack Notification
-        uses: act10ns/slack@v2.0.0
-        if: failure()
-        with:
-          status: ${{ job.status }}
-          steps: ${{ toJson(steps) }}
-          channel: ${{ secrets.SLACK_DEVOPS_CHANNEL }}
+      # - name: Slack Notification
+      #   uses: act10ns/slack@v2.0.0
+      #   if: failure()
+      #   with:
+      #     status: ${{ job.status }}
+      #     steps: ${{ toJson(steps) }}
+      #     channel: ${{ secrets.SLACK_DEVOPS_CHANNEL }}
     
   build-ubuntu-latest:
     if: ${{ inputs.type == 'ubuntu-latest' }}
