updates

diff --git a/.github/workflows/master_build_merge.yml b/.github/workflows/master_build_merge.yml
--- a/.github/workflows/master_build_merge.yml
+++ b/.github/workflows/master_build_merge.yml
@@ -18,18 +18,173 @@ on:
 
 jobs:
 
+  build-ui:
+    if: ${{ inputs.type == 'ui-build' }}
+    runs-on: ui-build
+    env:
+      LATEST_TAG: ${{inputs.tag}}
+      LABEL: ${{inputs.label}}
+      DOCKERHUB_ORG: ${{vars.DOCKERHUB_ORG}}
+      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
+      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
+      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
+      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
+      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
+      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      REPO: "${{github.event.pull_request.base.repo.name}}"
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4.1.1
+        with:
+          fetch-depth: 0
+
+      - name: Build
+        shell: bash
+        run: |
+          gradlewUI() {
+            set +e
+            rm ~/.npmrc
+            rm ~/.yarnrc
+            TOKEN=$(echo -n '${{env.NEXUS_USERNAME}}:${{env.NEXUS_PASSWORD}}' | base64 -w 0)
+            echo '"@tessell:registry" "${{env.NEXUS_PROTOCOL}}://${{env.NEXUS_SERVER_ENDPOINT}}/repository/${{vars.NEXUS_PUSH_REPOS_NPM}}/"' >> .yarnrc
+            echo "always-auth=true" >> .npmrc
+            echo "_auth=$TOKEN" >> .npmrc
+            cat .npmrc
+            cat .yarnrc
+            set -e
+            ./gradlew zipUiBuild  publish --console plain \
+              -Pnexus_push_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
+              -Pnexus_push_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
+              -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
+              -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
+              -Pnexus_push_repo_m2="${{ vars.NEXUS_PUSH_REPOS_M2 }}" \
+              -Pnexus_pull_repo_m2="${{ env.NEXUS_PULL_REPOS_M2 }}"
+            set +e
+          }
+          npmBuild() {
+            set -e
+            npm install
+            npm run build
+            set +e 
+            rm ~/.npmrc
+            TOKEN=$(echo -n '${{env.NEXUS_USERNAME}}:${{env.NEXUS_PASSWORD}}' | base64 -w 0)
+            echo "//${{ env.NEXUS_SERVER_ENDPOINT }}/repository/:_auth = $TOKEN" >> ~/.npmrc
+            echo "//${{ env.NEXUS_SERVER_ENDPOINT }}/repository/:always-auth = true" >> ~/.npmrc 
+            echo "@tessell:registry=${{env.NEXUS_PROTOCOL}}://${{ env.NEXUS_SERVER_ENDPOINT }}/repository/${{ vars.NEXUS_PUSH_REPOS_NPM }}" >> ~/.npmrc
+            cat ~/.npmrc
+            set -e
+            version="$3"
+            yq ".version = \"$version\"" package.json > tmp_package.json
+            mv tmp_package.json package.json
+            npm publish   
+            set +e
+          }
+          build() {
+            type="$1"
+            check=$(grep "$type" convoy.yaml)
+            if [[ -z "$check" ]]; then
+              return
+            fi
+            version=$(yq '.version' convoy.yaml)
+            while IFS=$'\t' read -r name buildFunction ext file _; do
+              echo "Name: $name"
+              echo "buildFunction: $buildFunction"
+              echo "Ext: $ext"
+              echo "Version: $version"
+              echo "dockerFile: $file"
+              $buildFunction "$name" "$ext" "$version" "$file"
+            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @tsv" convoy.yaml)
+          }
+          set +e
+          build "artifacts"
+          build "dockerImages"
+          build "helmCharts"
+                  
+      - name: Slack Notification
+        uses: act10ns/slack@v2.0.0
+        if: failure()
+        with:
+          status: ${{ job.status }}
+          steps: ${{ toJson(steps) }}
+          channel: ${{ secrets.SLACK_DEVOPS_CHANNEL }}
+    
+  build-ubuntu-latest:
+    if: ${{ inputs.type == 'ubuntu-latest' }}
+    runs-on: ubuntu-latest
+    env:
+      LATEST_TAG: ${{inputs.tag}}
+      LABEL: ${{inputs.label}}
+      DOCKERHUB_ORG: ${{vars.DOCKERHUB_ORG}}
+      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
+      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
+      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_PUBLIC}}
+      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
+      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_PUBLIC}}
+      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      REPO: "${{github.event.pull_request.base.repo.name}}"
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4.1.1
+        with:
+          fetch-depth: 0
+
+      - name: Build
+        shell: bash
+        run: |
+          build() {
+            type="$1"
+            check=$(grep "$type" convoy.yaml)
+            if [[ -z "$check" ]]; then
+              return
+            fi
+            version=$(yq '.version' convoy.yaml)
+            while IFS=$'\t' read -r name buildFunction ext file _; do
+              echo "Name: $name"
+              echo "buildFunction: $buildFunction"
+              echo "Ext: $ext"
+              echo "Version: $version"
+              echo "dockerFile: $file"
+              $buildFunction "$name" "$ext" "$version" "$file"
+            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @tsv" convoy.yaml)
+          }
+          set +e
+          build "artifacts"
+          build "dockerImages"
+          build "helmCharts"
+
+      - name: Cleanup
+        if: always()
+        run: |
+          set +e
+          docker container prune --force
+          docker volume prune --force
+                  
+      - name: Slack Notification
+        uses: act10ns/slack@v2.0.0
+        if: failure()
+        with:
+          status: ${{ job.status }}
+          steps: ${{ toJson(steps) }}
+          channel: ${{ secrets.SLACK_DEVOPS_CHANNEL }}
+      
   build-amd:
-    if: ${{ inputs.type != 'arm' }}
+    if: ${{ (inputs.type != 'arm' && inputs.type != 'ui-build' && inputs.type != 'ubuntu-latest') || inputs.type == 'amd' }}
     runs-on: self-hosted
     env:
       LATEST_TAG: ${{inputs.tag}}
       LABEL: ${{inputs.label}}
       DOCKERHUB_ORG: ${{vars.DOCKERHUB_ORG}}
-      REPO: "${{github.event.pull_request.base.repo.name}}"
-      NEXUS_PULL_REPOS_M2: tessell-m2-development
       GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
       GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
-      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
+      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
+      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
+      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
+      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      REPO: "${{github.event.pull_request.base.repo.name}}"
+      NEXUS_PULL_REPOS_M2: tessell-m2-development
     steps:
       - name: Checkout code
         uses: actions/checkout@v4.1.1
@@ -53,29 +208,8 @@ jobs:
               FILE="./Dockerfile"
             fi
             echo "$FILE"
-            ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
             docker build -f $FILE -t ${DOCKERHUB_ORG}/$IMAGE_NAME:${LATEST_TAG} .
             docker push ${DOCKERHUB_ORG}/$IMAGE_NAME:${LATEST_TAG}
-            set +e
-          }
-          gradlewUI() {
-            set +e
-            rm ~/.npmrc
-            rm ~/.yarnrc
-            TOKEN=$(echo -n '${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}}' | base64 -w 0)
-            echo '"@tessell:registry" "https://${{ vars.NEXUS_SERVER_ENDPOINT }}/repository/${{ vars.NEXUS_PUSH_REPOS_NPM }}/"' >> .yarnrc
-            echo "always-auth=true" >> .npmrc
-            echo "_auth=$TOKEN" >> .npmrc
-            cat .npmrc
-            cat .yarnrc
-            set -e
-            ./gradlew zipUiBuild  publish --console plain \
-              -Pnexus_push_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
-              -Pnexus_push_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
-              -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
-              -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
-              -Pnexus_push_repo_m2="${{ vars.NEXUS_PUSH_REPOS_M2 }}" \
-              -Pnexus_pull_repo_m2="${{ env.NEXUS_PULL_REPOS_M2 }}"
             set +e
           }
           helm-chart() {
@@ -87,19 +221,27 @@ jobs:
           }
           helm-template() {
             if [[ ${{steps.outputs.changed-files.any_modified}} == 'true' ]]; then
+              CHART_NAME="$1"
               GITHUB_WORKSPACE=$(pwd)
               CHART_GITHUB_LOCATION=$GITHUB_WORKSPACE
               TEMPLATE_REPO_GITHUB_LOCATION=$GITHUB_WORKSPACE/../convoy-helm-template
               echo "$CHART_GITHUB_LOCATION"
               echo "$TEMPLATE_REPO_GITHUB_LOCATION"
+              echo "TEMPLATE_REPO_GITHUB_LOCATION=$TEMPLATE_REPO_GITHUB_LOCATION"
               echo "Cloning convoy-helm-template"
               rm -rf $TEMPLATE_REPO_GITHUB_LOCATION
-              git clone https://github.com/TessellDevelopment/convoy-helm-template.git $TEMPLATE_REPO_GITHUB_LOCATION
+              template_version=$(yq --exit-status '.convoy-helm-template' Chart.yaml)
+              if [ $? -eq 0 ]; then
+                  echo "convoy-helm-template version: $template_version"
+              else
+                  echo "convoy-helm-template version not found.Exiting."
+                  exit 1
+              fi
+              git clone --branch $template_version https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${{github.repository_owner}}/convoy-helm-template.git $TEMPLATE_REPO_GITHUB_LOCATION
               echo "Copying the service values file"
               cp -r $CHART_GITHUB_LOCATION/services/* $TEMPLATE_REPO_GITHUB_LOCATION/helm-chart/values/apps/
               cp -r $CHART_GITHUB_LOCATION/Chart.yaml $TEMPLATE_REPO_GITHUB_LOCATION/helm-chart/Chart.yaml
               set -e
-              CHART_NAME=$(grep 'name' convoy.yaml | awk '{print $2}')
               cd $TEMPLATE_REPO_GITHUB_LOCATION/scripts
               ls -lrta ../helm-chart/values/apps/
               echo "Running package and push"
@@ -107,22 +249,10 @@ jobs:
               set +e
             fi
           }
-          npmBuild() {
+          opsImageBuild() {
             set -e
-            npm install
-            npm run build
-            set +e 
-            rm ~/.npmrc
-            TOKEN=$(echo -n '${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}}' | base64 -w 0)
-            echo "//${{ vars.NEXUS_SERVER_ENDPOINT }}/repository/:_auth = $TOKEN" >> ~/.npmrc
-            echo "//${{ vars.NEXUS_SERVER_ENDPOINT }}/repository/:always-auth = true" >> ~/.npmrc 
-            echo "@tessell:registry=https://${{ vars.NEXUS_SERVER_ENDPOINT }}/repository/${{ vars.NEXUS_PUSH_REPOS_NPM }}" >> ~/.npmrc
-            cat ~/.npmrc
-            set -e
-            version=$(cat convoy.yaml | yq -r '.version')
-            yq ".version = \"$version\"" package.json > tmp_package.json
-            mv tmp_package.json package.json
-            npm publish   
+            ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
+            dockerBuild "$1" "$2" "$3" "$4"
             set +e
           }
           build() {
@@ -131,28 +261,29 @@ jobs:
             if [[ -z "$check" ]]; then
               return
             fi
-            while IFS=$'\t' read -r name buildFunction ext version file _; do
+            version=$(yq '.version' convoy.yaml)
+            while IFS=$'\t' read -r name buildFunction ext file _; do
               echo "Name: $name"
               echo "buildFunction: $buildFunction"
               echo "Ext: $ext"
               echo "Version: $version"
               echo "dockerFile: $file"
               $buildFunction "$name" "$ext" "$version" "$file"
-            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .version, .dockerFile] | @tsv" convoy.yaml)
+            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @tsv" convoy.yaml)
           }
           set +e
           build "artifacts"
           build "dockerImages"
           build "helmCharts"
 
-      - name: Remove target
+      - name: Cleanup
         if: always()
         run: |
           set +e
           sudo rm -rf target
           docker container prune --force
           docker volume prune --force
-
+                  
       - name: Slack Notification
         uses: act10ns/slack@v2.0.0
         if: failure()
@@ -160,7 +291,7 @@ jobs:
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: ${{ secrets.SLACK_DEVOPS_CHANNEL }}
-
+      
   build-arm:
     if: ${{ inputs.type == 'arm' }}
     runs-on: ARM64
@@ -169,8 +300,12 @@ jobs:
       LABEL: ${{inputs.label}}
       DOCKERHUB_ORG: ${{vars.DOCKERHUB_ORG}}
       REPO: "${{github.event.pull_request.base.repo.name}}"
-      GITHUB_USER: ${{ secrets.CIPIPELINE_NEXUS_USERNAME }}
-      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
+      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
+      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
+      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
+      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
+      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
     steps: 
       - name: Checkout code
@@ -191,15 +326,16 @@ jobs:
       - name: Build and Push OPS
         shell: bash
         run: |
-          mvnwBuild() {
+          dockerBuild() {
             set -e
-            NAME="$1"
-            ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
-            curl -v -u ${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}} \
-              --upload-file ./target/function.zip \
-              https://${{vars.NEXUS_SERVER_ENDPOINT}}/repository/${{vars.NEXUS_REPO_TESSELLOPS_ARTIFACTS}}/${LABEL}/$NAME/$NAME-${LATEST_TAG}.zip
-            mv ./target/function.zip  $NAME-${LATEST_TAG}.zip
-            aws s3 cp $NAME-${LATEST_TAG}.zip s3://${{vars.TESSELLOPS_ARTIFACTS_DEV_S3}}/${LABEL}/$NAME/$NAME-${LATEST_TAG}.zip   
+            IMAGE_NAME="$1"
+            FILE="$4"
+            if [[ "$FILE" == "null" || -z "$FILE" ]]; then
+              FILE="./Dockerfile"
+            fi
+            echo "$FILE"
+            docker build -f $FILE -t ${DOCKERHUB_ORG}/$IMAGE_NAME:${LATEST_TAG} .
+            docker push ${DOCKERHUB_ORG}/$IMAGE_NAME:${LATEST_TAG}
             set +e
           }
           jarBuild() {
@@ -209,17 +345,22 @@ jobs:
             # Add Build Function
             set +e
           }
-          dockerBuild() {
+          mvnwBuild() {
             set -e
-            IMAGE_NAME="$1"
-            FILE="$4"
-            if [[ "$FILE" == "null" || -z "$FILE" ]]; then
-              FILE="./Dockerfile"
-            fi
-            echo "$FILE"
-             ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
-             docker build -f $FILE -t ${DOCKERHUB_ORG}/$IMAGE_NAME:${LATEST_TAG} .
-             docker push ${DOCKERHUB_ORG}/$IMAGE_NAME:${LATEST_TAG}
+            NAME="$1"
+            ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
+            curl -v -u ${{env.NEXUS_USERNAME}}:${{env.NEXUS_PASSWORD}} \
+              --upload-file ./target/function.zip \
+              ${{env.NEXUS_PROTOCOL}}://${{env.NEXUS_SERVER_ENDPOINT}}/repository/${{vars.NEXUS_REPO_TESSELLOPS_ARTIFACTS}}/${LABEL}/$NAME/$NAME-${LATEST_TAG}.zip
+            mv ./target/function.zip  $NAME-${LATEST_TAG}.zip
+            aws s3 cp $NAME-${LATEST_TAG}.zip s3://${{vars.TESSELLOPS_ARTIFACTS_DEV_S3}}/${LABEL}/$NAME/$NAME-${LATEST_TAG}.zip   
+            set +e
+          }
+          opsImageBuild() {
+            set -e
+            NAME="$1"
+            ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
+            dockerBuild "$1" "$2" "$3" "$4"
             set +e
           }
           build() {
@@ -228,20 +369,21 @@ jobs:
             if [[ -z "$check" ]]; then
               return
             fi
-            while IFS=$'\t' read -r name buildFunction ext version file _; do
+            version=$(yq '.version' convoy.yaml)
+            while IFS=$'\t' read -r name buildFunction ext file _; do
               echo "Name: $name"
               echo "buildFunction: $buildFunction"
               echo "Ext: $ext"
               echo "Version: $version"
               echo "dockerFile: $file"
               $buildFunction "$name" "$ext" "$version" "$file"
-            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .version, .dockerFile] | @tsv" convoy.yaml)
+            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @tsv" convoy.yaml)
           }
           set +e
           build "artifacts"
           build "dockerImages"
 
-      - name: Remove target
+      - name: Cleanup
         if: always()
         run: |
           set +e
@@ -256,4 +398,3 @@ jobs:
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: ${{ secrets.SLACK_DEVOPS_CHANNEL }}
-    
diff --git a/.github/workflows/master_build_pr.yml b/.github/workflows/master_build_pr.yml
--- a/.github/workflows/master_build_pr.yml
+++ b/.github/workflows/master_build_pr.yml
@@ -10,11 +10,130 @@ on:
 
 jobs:
 
-  build-amd:
-    if: ${{ inputs.type != 'arm' }}
-    runs-on: self-hosted
+  build-ui:
+    if: ${{ inputs.type == 'ui-build' }}
+    runs-on: ui-build
     env:
       NEXUS_REPO_NPM: tessell-repos-npm-development
+      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
+      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
+      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
+      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
+      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4.1.1
+        with:
+          fetch-depth: 0
+
+      - name: Build
+        shell: bash
+        run: |
+          gradlewUI() {
+            rm ~/.npmrc
+            rm ~/.yarnrc
+            TOKEN=$(echo -n '${{vars.NEXUS_USERNAME}}:${{vars.NEXUS_PASSWORD}}' | base64 -w 0)
+            echo '"@tessell:registry" "${{env.NEXUS_PROTOCOL}}://${{env.NEXUS_SERVER_ENDPOINT}}/repository/${{vars.NEXUS_PUSH_REPOS_NPM}}/"' >> .yarnrc
+            echo "always-auth=true" >> .npmrc
+            echo "_auth=$TOKEN" >> .npmrc
+            cat .npmrc
+            cat .yarnrc
+            set -e
+            ./gradlew zipUiBuild --console plain --stacktrace \
+              -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
+              -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}"
+            set +e
+          }
+          npmBuild() {
+            set -e
+            npm install
+            npm run build
+            set +e 
+            rm ~/.npmrc
+            TOKEN=$(echo -n '${{vars.NEXUS_USERNAME}}:${{vars.NEXUS_PASSWORD}}' | base64 -w 0)
+            echo "//${{env.NEXUS_SERVER_ENDPOINT}}/repository/:_auth = $TOKEN" >> ~/.npmrc
+            echo "//${{env.NEXUS_SERVER_ENDPOINT}}/repository/:always-auth = true" >> ~/.npmrc 
+            echo "@tessell:registry=${{env.NEXUS_PROTOCOL}}://${{env.NEXUS_SERVER_ENDPOINT}}/repository/${{ env.NEXUS_REPO_NPM }}" >> ~/.npmrc
+            cat ~/.npmrc
+            set -e
+            version="$3"
+            yq ".version = \"$version\"" package.json > tmp_package.json
+            mv tmp_package.json package.json
+            npm publish   
+            set +e
+          }
+          build() {
+            type="$1"
+            check=$(grep "$type" convoy.yaml)
+            if [[ -z "$check" ]]; then
+              return
+            fi
+            version=$(yq '.version' convoy.yaml)
+            while IFS=$'\t' read -r name buildFunction ext file _; do
+              echo "Name: $name"
+              echo "buildFunction: $buildFunction"
+              echo "Ext: $ext"
+              echo "Version: $version"
+              echo "dockerFile: $file"
+              $buildFunction "$name" "$ext" "$version" "$file"
+            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @tsv" convoy.yaml)
+          }
+          set +e
+          build "artifacts"
+          build "dockerImages"
+          build "helmCharts"
+  
+  build-ubuntu-latest:
+    if: ${{ inputs.type == 'ubuntu-latest' }}
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
+      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
+      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_PUBLIC}}
+      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
+      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_PUBLIC}}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4.1.1
+        with:
+          fetch-depth: 0
+
+      - name: Build
+        shell: bash
+        run: |
+          build() {
+            type="$1"
+            check=$(grep "$type" convoy.yaml)
+            if [[ -z "$check" ]]; then
+              return
+            fi
+            version=$(yq '.version' convoy.yaml)
+            while IFS=$'\t' read -r name buildFunction ext file _; do
+              echo "Name: $name"
+              echo "buildFunction: $buildFunction"
+              echo "Ext: $ext"
+              echo "Version: $version"
+              echo "dockerFile: $file"
+              $buildFunction "$name" "$ext" "$version" "$file"
+            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @tsv" convoy.yaml)
+          }
+          set +e
+          build "artifacts"
+          build "dockerImages"
+          build "helmCharts"
+
+  build-amd:
+    if: ${{ (inputs.type != 'arm' && inputs.type != 'ui-build' && inputs.type != 'ubuntu-latest') || inputs.type == 'amd' }}
+    runs-on: self-hosted
+    env:
+      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
+      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
+      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
+      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
+      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4.1.1
@@ -40,27 +159,7 @@ jobs:
               FILE="./Dockerfile"
             fi
             echo "$FILE"
-            ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
-            echo "Complete"
-            echo "$FILE"
-            echo "Starting Docker"
             docker build -f $FILE -t $IMAGE_NAME .
-            set +e
-          }
-          gradlewUI() {
-            set +e
-            rm ~/.npmrc
-            rm ~/.yarnrc
-            TOKEN=$(echo -n '${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}}' | base64 -w 0)
-            echo '"@tessell:registry" "https://${{ vars.NEXUS_SERVER_ENDPOINT }}/repository/${{ vars.NEXUS_PUSH_REPOS_NPM }}/"' >> .yarnrc
-            echo "always-auth=true" >> .npmrc
-            echo "_auth=$TOKEN" >> .npmrc
-            cat .npmrc
-            cat .yarnrc
-            set -e
-            ./gradlew zipUiBuild --console plain --stacktrace \
-              -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
-              -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}"
             set +e
           }
           helm-chart() {
@@ -71,20 +170,28 @@ jobs:
             set +e
           }
           helm-template() {
-            if [[ ${{steps.outputs.changed-files.any_modified}} == 'true' ]]; then
+            if [[ ${{steps.changed-files.outputs.any_modified}} == 'true' ]]; then
+              CHART_NAME="$1"
               GITHUB_WORKSPACE=$(pwd)
               CHART_GITHUB_LOCATION=$GITHUB_WORKSPACE
               TEMPLATE_REPO_GITHUB_LOCATION=$GITHUB_WORKSPACE/../convoy-helm-template
               echo "$CHART_GITHUB_LOCATION"
               echo "$TEMPLATE_REPO_GITHUB_LOCATION"
+              echo "TEMPLATE_REPO_GITHUB_LOCATION=$TEMPLATE_REPO_GITHUB_LOCATION"
               echo "Cloning convoy-helm-template"
               rm -rf $TEMPLATE_REPO_GITHUB_LOCATION
-              git clone https://github.com/TessellDevelopment/convoy-helm-template.git $TEMPLATE_REPO_GITHUB_LOCATION
+              template_version=$(yq --exit-status '.convoy-helm-template' Chart.yaml)
+              if [ $? -eq 0 ]; then
+                  echo "convoy-helm-template version: $template_version"
+              else
+                  echo "convoy-helm-template version not found.Exiting."
+                  exit 1
+              fi
+              git clone --branch $template_version https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${{github.repository_owner}}/convoy-helm-template.git $TEMPLATE_REPO_GITHUB_LOCATION
               echo "Copying the service values file"
               cp -r $CHART_GITHUB_LOCATION/services/* $TEMPLATE_REPO_GITHUB_LOCATION/helm-chart/values/apps/
               cp -r $CHART_GITHUB_LOCATION/Chart.yaml $TEMPLATE_REPO_GITHUB_LOCATION/helm-chart/Chart.yaml
               set -e
-              CHART_NAME=$(grep 'name' convoy.yaml | awk '{print $2}')
               cd $TEMPLATE_REPO_GITHUB_LOCATION/scripts
               ls -lrta ../helm-chart/values/apps/
               echo "Running package and push"
@@ -92,22 +199,15 @@ jobs:
               set +e
             fi
           }
-          npmBuild() {
+          mvnwBuild() {
             set -e
-            npm install
-            npm run build
-            set +e 
-            rm ~/.npmrc
-            TOKEN=$(echo -n '${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}}' | base64 -w 0)
-            echo "//${{ vars.NEXUS_SERVER_ENDPOINT }}/repository/:_auth = $TOKEN" >> ~/.npmrc
-            echo "//${{ vars.NEXUS_SERVER_ENDPOINT }}/repository/:always-auth = true" >> ~/.npmrc 
-            echo "@tessell:registry=https://${{ vars.NEXUS_SERVER_ENDPOINT }}/repository/${{ env.NEXUS_REPO_NPM }}" >> ~/.npmrc
-            cat ~/.npmrc
+            ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
+            set +e
+          }
+          opsImageBuild() {
             set -e
-            version=$(cat convoy.yaml | yq -r '.version')
-            yq ".version = \"$version\"" package.json > tmp_package.json
-            mv tmp_package.json package.json
-            npm publish   
+            mvnwBuild
+            dockerBuild "$1" "$2" "$3" "$4"
             set +e
           }
           build() {
@@ -116,21 +216,21 @@ jobs:
             if [[ -z "$check" ]]; then
               return
             fi
-            while IFS=$'\t' read -r name buildFunction ext version file _; do
+            version=$(yq '.version' convoy.yaml)
+            while IFS=$'\t' read -r name buildFunction ext file _; do
               echo "Name: $name"
               echo "buildFunction: $buildFunction"
               echo "Ext: $ext"
-              echo "Version: $version"
               echo "dockerFile: $file"
               $buildFunction "$name" "$ext" "$version" "$file"
-            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .version, .dockerFile] | @tsv" convoy.yaml)
+            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @tsv" convoy.yaml)
           }
           set +e
           build "artifacts"
           build "dockerImages"
           build "helmCharts"
 
-      - name: Remove target
+      - name: Cleanup
         if: always()
         run: |
           set +e
@@ -141,6 +241,13 @@ jobs:
   build-arm:
     if: ${{ inputs.type == 'arm' }}
     runs-on: ARM64
+    env:
+      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
+      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
+      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
+      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
+      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
+      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4.1.1
@@ -150,16 +257,6 @@ jobs:
       - name: Build
         shell: bash
         run: |
-          mvnwBuild() {
-            set -e
-             ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
-            set +e
-          }
-          jarBuild() {
-            set -e
-            ./mvnw package -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
-            set +e
-          }
           dockerBuild() {
             set -e
             IMAGE_NAME="$1"
@@ -168,9 +265,23 @@ jobs:
               FILE="./Dockerfile"
             fi
             echo "$FILE"
-            mvnwBuild
-            set -e
             docker build -f $FILE -t $IMAGE_NAME .
+            set +e
+          }
+          jarBuild() {
+            set -e
+            ./mvnw package -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
+            set +e
+          }
+          mvnwBuild() {
+            set -e
+            ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
+            set +e
+          }
+          opsImageBuild() {
+            set -e
+            mnwBuild
+            dockerBuild "$1" "$2" "$3" "$4"
             set +e
           }
           build() {
@@ -179,20 +290,20 @@ jobs:
             if [[ -z "$check" ]]; then
               return
             fi
-            while IFS=$'\t' read -r name buildFunction ext version file _; do
+            version=$(yq '.version' convoy.yaml)
+            while IFS=$'\t' read -r name buildFunction ext file _; do
               echo "Name: $name"
               echo "buildFunction: $buildFunction"
               echo "Ext: $ext"
-              echo "Version: $version"
               echo "dockerFile: $file"
               $buildFunction "$name" "$ext" "$version" "$file"
-            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .version, .dockerFile] | @tsv" convoy.yaml)
+            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @tsv" convoy.yaml)
           }
           set +e
           build "artifacts"
           build "dockerImages"
 
-      - name: Remove target
+      - name: Cleanup
         if: always()
         run: |
           set +e
