TDEVOPS-1250 | POST API update in Master_CI (#199)
* added uses_custom_version

* using python3

* changed ref

* updates

* getting modules from base branch

diff --git a/.github/workflows/master_create_tag.yml b/.github/workflows/master_create_tag.yml
--- a/.github/workflows/master_create_tag.yml
+++ b/.github/workflows/master_create_tag.yml
@@ -11,6 +11,9 @@ on:
       tag:
         description: "New tag created post merge"
         value: ${{ jobs.create-tag-on-merge.outputs.tag_ref_output }}
+      uses_custom_version:
+        description: "Key for using tag as version"
+        value: ${{ jobs.create-tag-on-merge.outputs.uses_custom_version }}
 
 jobs:
 
@@ -22,10 +25,14 @@ jobs:
       LABEL: ${{inputs.label}}
     outputs:
       tag_ref_output: ${{ steps.tag_output.outputs.tag_ref }}
+      uses_custom_version: ${{ steps.tag_output.outputs.uses_custom_version }}
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
+      - name: Install dependencies
+        run: npm install js-yaml --force
 
       - name: Find latest tag
         id: latest_tag
@@ -41,61 +48,79 @@ jobs:
         with:
           github-token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}
           script: |
-            latest_tag = '0.0.0'
-            // process multiple tags if any
-            tags = "${{ env.TAGS }}".split(' ')
-            if (tags.length == 1) {
-              latest_tag = tags[0]
-            } else {
-              if ("${{ github.event.pull_request.base.ref }}" == "main") {
-                for (i in tags) {
-                  tag = tags[i]
-                  console.log("Checking tag " + tag)
-                  if (latest_tag == null) {
-                    latest_tag = tag
-                    continue
-                  }
-                  latest_parts = latest_tag.split(".")
-                  tag_parts = tag.split(".")
-                  for (i = 0; i < tag_parts.length; i++) {
-                    if (parseInt(tag_parts[i]) < parseInt(latest_parts[i])) {
-                      console.log("Skipping " + tag)
-                      break
-                    }
-                    if (parseInt(tag_parts[i]) > parseInt(latest_parts[i])) {
-                      latest_tag = tag
-                      console.log("Setting " + latest_tag)
-                      break
-                    }
-                  }
-                }
+            const fs = require('fs');
+            const yaml = require('js-yaml');
+            const content = fs.readFileSync('./convoy.yaml', 'utf8');
+            const data = yaml.load(content);
+            var language = data.language
+            var version = data.version
+            if (language === 'helm'){
+              const path = data.generates.helmCharts[0].chartPath
+              const contentHelm = fs.readFileSync(path, 'utf8');
+              const dataHelm = yaml.load(contentHelm);
+              new_tag = dataHelm.version
+              core.setOutput('uses_custom_version', "true")  
+            } else if (version !== undefined ){
+              new_tag = version
+              core.setOutput('uses_custom_version', "true")  
+            } else{
+              latest_tag = '0.0.0'
+              // process multiple tags if any
+              tags = "${{ env.TAGS }}".split(' ')
+              if (tags.length == 1) {
+                latest_tag = tags[0]
               } else {
-                tag_base = "${{ github.event.pull_request.base.ref }}".substring(4).split(".").slice(0,2)
-                latest_tag = tag_base.join(".") + ".0"
-                for (i in tags) {
-                  tag = tags[i]
-                  console.log("branch - Checking tag " + tag)
-                  tag_parts = tag.split(".")
-                  if (tag_base[0] == tag_parts[0] && tag_base[1] == tag_parts[1]) {
-                    latest_parts = latest_tag.split(".")
-                    if (parseInt(latest_parts[2]) < parseInt(tag_parts[2])) {
+                if ("${{ github.event.pull_request.base.ref }}" == "main") {
+                  for (i in tags) {
+                    tag = tags[i]
+                    console.log("Checking tag " + tag)
+                    if (latest_tag == null) {
                       latest_tag = tag
+                      continue
+                    }
+                    latest_parts = latest_tag.split(".")
+                    tag_parts = tag.split(".")
+                    for (i = 0; i < tag_parts.length; i++) {
+                      if (parseInt(tag_parts[i]) < parseInt(latest_parts[i])) {
+                        console.log("Skipping " + tag)
+                        break
+                      }
+                      if (parseInt(tag_parts[i]) > parseInt(latest_parts[i])) {
+                        latest_tag = tag
+                        console.log("Setting " + latest_tag)
+                        break
+                      }
+                    }
+                  }
+                } else {
+                  tag_base = "${{ github.event.pull_request.base.ref }}".substring(4).split(".").slice(0,2)
+                  latest_tag = tag_base.join(".") + ".0"
+                  for (i in tags) {
+                    tag = tags[i]
+                    console.log("branch - Checking tag " + tag)
+                    tag_parts = tag.split(".")
+                    if (tag_base[0] == tag_parts[0] && tag_base[1] == tag_parts[1]) {
+                      latest_parts = latest_tag.split(".")
+                      if (parseInt(latest_parts[2]) < parseInt(tag_parts[2])) {
+                        latest_tag = tag
+                      }
                     }
                   }
                 }
               }
-            }
-            console.log("Latest tag: " + latest_tag)
+              console.log("Latest tag: " + latest_tag)
 
-            // check if we have
-            if ( latest_tag == '' || latest_tag === undefined) {
-              console.log("Couldn't determine the latest tag, exiting. Retry manually..")
-              process.exit(1);
-            }
+              // check if we have
+              if ( latest_tag == '' || latest_tag === undefined) {
+                console.log("Couldn't determine the latest tag, exiting. Retry manually..")
+                process.exit(1);
+              }
 
-            // increase the minor version lineraly to get the new tag
-            tag_parts = latest_tag.split('.')
-            new_tag = [tag_parts[0], tag_parts[1], parseInt(tag_parts[2]) + 1].join('.')
+              // increase the minor version lineraly to get the new tag
+              tag_parts = latest_tag.split('.')
+              new_tag = [tag_parts[0], tag_parts[1], parseInt(tag_parts[2]) + 1].join('.')
+              core.setOutput('uses_custom_version', "false")  
+            }
 
             // head of the branch needs to be tagged
             sha_to_tag = "${{ github.event.pull_request.merge_commit_sha }}"
@@ -123,11 +148,56 @@ jobs:
                 ref: fullTagName,
                 sha: sha_to_tag
             });
-
             console.log('Ref updated.');
             core.setOutput('tag_ref', new_tag)  
 
+      - name: Tag Output
+        id: tag_output
+        run: |
+          echo "tag_ref=${{steps.create_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
+          echo "uses_custom_version=${{steps.create_tag.outputs.uses_custom_version}}" >> $GITHUB_OUTPUT
+
+      - name: Set Label
+        id: set_label
+        shell: bash
+        run: |
+          validate_label=false
+          if [ -f convoy.yaml ]; then
+            language=$(yq '.language' convoy.yaml)
+            version=$(yq '.version' convoy.yaml)
+            if [[ "$language" == "helm" ]]; then
+              echo "Helm repo, No validation needed using version as tag."
+            elif [[ "$version" != "null" ]]; then
+              echo "Version present in convoy.yaml, No validation needed using version as tag."
+            else
+              validate_label=true
+              if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
+                TOKEN=$(echo -n '${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}}' | base64 -w 0)
+                APP_GROUP=$(yq '.appGroup // "tessell"' convoy.yaml)
+                URL="http://${{vars.CONVOY_API_ENDPOINT}}/devops/applications/app-groups/$APP_GROUP/latest-main-release-label"
+                RESPONSE=$(curl -f --location "$URL" --header "Authorization: Basic $TOKEN")
+                echo "$RESPONSE"
+                LABEL=$(echo "$RESPONSE" | jq -r '.["latest-main-release-label"]')
+                echo "$LABEL"
+                if [[ $LABEL == rel-* ]]; then
+                    echo "LABEL=$LABEL" >> $GITHUB_ENV
+                else
+                    echo "Response: $LABEL"
+                    echo "Label does not start with 'rel'. Check response."
+                    exit 1 
+                fi
+              
+              else
+                echo "LABEL=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
+              fi
+            fi  
+           else
+            echo "convoy.yaml not found"
+           fi 
+           echo "validate_label=$validate_label" >> $GITHUB_OUTPUT
+
       - name: Validate Label
+        if: ${{ steps.set_label.outputs.validate_label == 'true' }}
         run: |
           tag=$(echo ${{steps.create_tag.outputs.tag_ref}} | cut -d '.' -f 2)
           label=$(echo ${{env.LABEL}} | cut -d '.' -f 2)
@@ -136,12 +206,7 @@ jobs:
           else
               echo "TAG and LABEL are on different release label. Please check git tag and API response."
               exit 1
-          fi   
-
-      - name: Tag Output
-        id: tag_output
-        run: |
-          echo "tag_ref=${{steps.create_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
+          fi  
 
       - name: Slack Notification
         if: failure()
