TDEVOPS-1848 | Add opsUIBuild

diff --git a/.github/workflows/master_build_merge.yml b/.github/workflows/master_build_merge.yml
--- a/.github/workflows/master_build_merge.yml
+++ b/.github/workflows/master_build_merge.yml
@@ -70,6 +70,16 @@ jobs:
             echo "@tessell:registry=${{env.NEXUS_PROTOCOL}}://${{ env.NEXUS_SERVER_ENDPOINT }}/repository/$REPO" >> ~/.npmrc
             cat ~/.npmrc
           }
+          configureNpmrcYarnrc() {
+            rm ~/.npmrc
+            rm ~/.yarnrc
+            TOKEN=$(echo -n '${{env.NEXUS_USERNAME}}:${{env.NEXUS_PASSWORD}}' | base64 -w 0)
+            echo '"@tessell:registry" "${{env.NEXUS_PROTOCOL}}://${{ env.NEXUS_SERVER_ENDPOINT }}/repository/${{ vars.NEXUS_PUSH_REPOS_NPM }}/"' >> .yarnrc
+            echo "always-auth=true" >> .npmrc
+            echo "_auth=$TOKEN" >> .npmrc
+            cat .npmrc
+            cat .yarnrc
+          }
           dockerBuild() {
             set -e
             IMAGE="$1"
@@ -103,15 +113,8 @@ jobs:
             set +e
           }
           gradlewUIBuild() {
-            rm ~/.npmrc
-            rm ~/.yarnrc
-            TOKEN=$(echo -n '${{env.NEXUS_USERNAME}}:${{env.NEXUS_PASSWORD}}' | base64 -w 0)
-            echo '"@tessell:registry" "${{env.NEXUS_PROTOCOL}}://${{ env.NEXUS_SERVER_ENDPOINT }}/repository/${{ vars.NEXUS_PUSH_REPOS_NPM }}/"' >> .yarnrc
-            echo "always-auth=true" >> .npmrc
-            echo "_auth=$TOKEN" >> .npmrc
-            cat .npmrc
-            cat .yarnrc
             set -e
+            configureNpmrcYarnrc
             ENV_JSON='${{secrets.TESSELL_UI_ENV_SECRET}}'
             echo "$ENV_JSON" | jq -r 'to_entries | .[] | "\(.key)=\"\(.value)\"" ' | sed '1s/^/\n/' >> .env
             cat .env
@@ -149,6 +152,32 @@ jobs:
             mv tmp_package.json package.json
             npm publish   
             set +e
+          }
+          opsUIBuildAndPush() {
+            set -e
+            ARTIFACT="${1}"
+            EXT="${2}"
+            gradlewUIBuild
+            sed -i '' 's/^export const ENV = EnvType\.Development;$/export const ENV = EnvType\.Production;/g' src/constants/env.ts
+            pushToNexus "./build/libs/tessellops-ui-${LATEST_TAG}.zip" "${{vars.NEXUS_REPO_TESSELLOPS_ARTIFACTS}}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.${EXT}"
+            set +e
+          }
+          pushToNexus() {
+            FILE_PATH="$1"
+            URL_PATH="$2"
+            requiredInputs="1 2"
+            validateInputs "$requiredInputs" "$@" 
+            RESPONSE=$(curl -v -u ${{env.NEXUS_USERNAME}}:${{env.NEXUS_PASSWORD}} \
+                --upload-file $FILE_PATH  -w "%{http_code}" \
+                ${{env.NEXUS_PROTOCOL}}://${{env.NEXUS_SERVER_ENDPOINT}}/repository/$URL_PATH)
+            echo $REPONSE
+            HTTP_CODE=$(echo "$RESPONSE" | tail -n1) 
+            echo $HTTP_CODE
+            HTTP_CODE=$((HTTP_CODE))
+            if [ "$HTTP_CODE" -ne 201 ]; then
+              echo "Error: Unexpected HTTP response code $HTTP_CODE"
+              exit 1
+            fi
           }
           validateInputs() {
             local required=($1)
