updates

diff --git a/.github/workflows/master_find_latest_tag.yml b/.github/workflows/master_find_latest_tag.yml
--- a/.github/workflows/master_find_latest_tag.yml
+++ b/.github/workflows/master_find_latest_tag.yml
@@ -35,88 +35,88 @@ jobs:
               core.setOutput('commit_id', "${{ github.event.after }}" )
             }
               
-        - name: Get tags
-          uses: nick-fields/retry@v2.8.1
-          if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
-          with:
-            timeout_seconds: 10
-            max_attempts: 3
-            retry_on: error
-            command: |
-              git fetch --all
-              git tag --contains '${{ steps.find_commit.outputs.commit_id}}'
-              latest_tags+=("$(git tag --contains '${{ steps.find_commit.outputs.commit_id }}')")
-              if [[ "$latest_tags" == '' ]]; then 
-                echo " Tag is Empty"
-                exit 1
-              fi
-              echo "Tag is present: $latest_tags"       
-              for tag in $latest_tags; do tag_arr+=($tag); done
-              echo "TAGS=${tag_arr[@]}" >> $GITHUB_ENV
+      - name: Get tags
+        uses: nick-fields/retry@v2.8.1
+        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
+        with:
+          timeout_seconds: 10
+          max_attempts: 3
+          retry_on: error
+          command: |
+            git fetch --all
+            git tag --contains '${{ steps.find_commit.outputs.commit_id}}'
+            latest_tags+=("$(git tag --contains '${{ steps.find_commit.outputs.commit_id }}')")
+            if [[ "$latest_tags" == '' ]]; then 
+              echo " Tag is Empty"
+              exit 1
+            fi
+            echo "Tag is present: $latest_tags"       
+            for tag in $latest_tags; do tag_arr+=($tag); done
+            echo "TAGS=${tag_arr[@]}" >> $GITHUB_ENV
         
         
-        - name: Find latest tag
-          uses: actions/github-script@v6.3.3
-          id: latest_tag
-          if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
-          with:
-            github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
-            script: |
-              console.log("Tags are " + "${{ env.TAGS }}")
-              latest_tag = '0.0.0'
-              // process multiple tags if any
-              tags = "${{ env.TAGS }}".split(' ')
-              if (tags.length == 1) {
-                console.log("There is only one tag. Using it." + tags[0])
-                latest_tag = tags[0]
-              } else {
-                if ("${{ env.SOURCE_BRANCH }}" == "main") {
-                  for (i in tags) {
-                    tag = tags[i]
-                    console.log("Checking tag " + tag)
-                    if (latest_tag == null) {
-                      latest_tag = tag
-                      continue
+      - name: Find latest tag
+        uses: actions/github-script@v6.3.3
+        id: latest_tag
+        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
+        with:
+          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
+          script: |
+            console.log("Tags are " + "${{ env.TAGS }}")
+            latest_tag = '0.0.0'
+            // process multiple tags if any
+            tags = "${{ env.TAGS }}".split(' ')
+            if (tags.length == 1) {
+              console.log("There is only one tag. Using it." + tags[0])
+              latest_tag = tags[0]
+            } else {
+              if ("${{ env.SOURCE_BRANCH }}" == "main") {
+                for (i in tags) {
+                  tag = tags[i]
+                  console.log("Checking tag " + tag)
+                  if (latest_tag == null) {
+                    latest_tag = tag
+                    continue
+                  }
+                  latest_parts = latest_tag.split(".")
+                  tag_parts = tag.split(".")
+                  for (i = 0; i < tag_parts.length; i++) {
+                    if (parseInt(tag_parts[i]) < parseInt(latest_parts[i])) {
+                      console.log("Skipping " + tag)
+                      break
                     }
-                    latest_parts = latest_tag.split(".")
-                    tag_parts = tag.split(".")
-                    for (i = 0; i < tag_parts.length; i++) {
-                      if (parseInt(tag_parts[i]) < parseInt(latest_parts[i])) {
-                        console.log("Skipping " + tag)
-                        break
-                      }
-                      if (parseInt(tag_parts[i]) > parseInt(latest_parts[i])) {
-                        latest_tag = tag
-                        console.log("Setting " + latest_tag)
-                        break
-                      }
+                    if (parseInt(tag_parts[i]) > parseInt(latest_parts[i])) {
+                      latest_tag = tag
+                      console.log("Setting " + latest_tag)
+                      break
                     }
                   }
-                } else {
-                  tag_base = "${{ env.SOURCE_BRANCH }}".substring(4).split(".").slice(0,2)
-                  latest_tag = tag_base.join(".") + ".0"
-                  for (i in tags) {
-                    tag = tags[i]
-                    console.log("branch - Checking tag " + tag)
-                    tag_parts = tag.split(".")
-                    if (tag_base[0] == tag_parts[0] && tag_base[1] == tag_parts[1]) {
-                      latest_parts = latest_tag.split(".")
-                      if (parseInt(latest_parts[2]) < parseInt(tag_parts[2])) {
-                        latest_tag = tag
-                      }
+                }
+              } else {
+                tag_base = "${{ env.SOURCE_BRANCH }}".substring(4).split(".").slice(0,2)
+                latest_tag = tag_base.join(".") + ".0"
+                for (i in tags) {
+                  tag = tags[i]
+                  console.log("branch - Checking tag " + tag)
+                  tag_parts = tag.split(".")
+                  if (tag_base[0] == tag_parts[0] && tag_base[1] == tag_parts[1]) {
+                    latest_parts = latest_tag.split(".")
+                    if (parseInt(latest_parts[2]) < parseInt(tag_parts[2])) {
+                      latest_tag = tag
                     }
                   }
                 }
               }
-              console.log("Latest tag: " + latest_tag)
-              // check if we have
-              if ( latest_tag == '' || latest_tag === undefined) {
-                console.log("Couldn't determine the latest tag, exiting. Retry manually..")
-                process.exit(1);
-              }
-              core.setOutput('tag_ref', latest_tag)
+            }
+            console.log("Latest tag: " + latest_tag)
+            // check if we have
+            if ( latest_tag == '' || latest_tag === undefined) {
+              console.log("Couldn't determine the latest tag, exiting. Retry manually..")
+              process.exit(1);
+            }
+            core.setOutput('tag_ref', latest_tag)
 
-        - name: Tag Output
-          id: tag_output
-          run: |
-            echo "tag_ref=${{steps.latest_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
+      - name: Tag Output
+        id: tag_output
+        run: |
+          echo "tag_ref=${{steps.latest_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
