refactor

diff --git a/.github/workflows/master_build_merge.yml b/.github/workflows/master_build_merge.yml
--- a/.github/workflows/master_build_merge.yml
+++ b/.github/workflows/master_build_merge.yml
@@ -1501,49 +1501,6 @@ jobs:
             ls -lrta $BUILD_DIR
             set +e
           }
-          tsmZipBuild() {
-            set -e
-            ARTIFACT="$1"
-            requiredInputs="1"
-            validateInputs "$requiredInputs" "$@" 
-            mkdir -p build; cd tsmv101; terraform_build $PWD ../build/$ARTIFACT.zip; cd ../build; ls -l;
-            unzip -l $ARTIFACT.zip
-            cd ..
-            set +e
-          }
-          tsmZipBuildAndPush() {
-            tsmZipBuild "$@"
-            set -e
-            ARTIFACT="$1"
-            EXTENSION="$2"
-            VERSION="$3"
-            requiredInputs="1 2 3"
-            validateInputs "$requiredInputs" "$@" 
-            mvnDeploy "$ARTIFACT" "$EXTENSION" "build/$ARTIFACT.$EXTENSION" "tessell.tsm.infra" "$VERSION"
-            set +e
-          }
-          vssTarBuild() {
-            set -e
-            ARTIFACT="$1"
-            EXTENSION="$2"
-            CLOUD=$(echo "$ARTIFACT" | awk -F'[-]' '{print $3}')
-            DIR="build_$CLOUD"
-            mkdir $DIR
-            cp -r  ../tessell-vss/tessell-vss-requestor/TessellVssRequestor.exe ../tessell-vss/tessell-vss-provider/$CLOUD/install-provider $DIR
-            cd $DIR
-            tar -cf ../$ARTIFACT.$EXTENSION .
-            cd ..
-            ls
-            set +e
-          }
-          vssTarBuildAndPush() {
-            vssTarBuild "$@"
-            set -e
-            ARTIFACT="$1"
-            EXTENSION="$2"
-            mvnDeploy "$ARTIFACT" "$EXTENSION" "./$ARTIFACT.$EXTENSION" "tessell.vss" "${{env.LATEST_TAG}}"
-            set +e
-          }
           validateInputs() {
             local required=($1)
             shift
@@ -1721,6 +1678,21 @@ jobs:
               set +e
             fi
           }
+          mvnDeploy() {
+            ARTIFACT_ID="$1"
+            EXTENSION="$2"
+            FILE="$3"
+            GROUP_ID="$4"
+            VERSION="$5"
+            requiredInputs="1 2 3 4 5"
+            validateInputs "$requiredInputs" "$@" 
+            mvn deploy:deploy-file -Dnexus_url=${{env.NEXUS_PROTOCOL}}://${{env.NEXUS_SERVER_ENDPOINT}}/repository/tessell-m2-component \
+                -Dnexus_username=${NEXUS_USERNAME} -Dnexus_password=${NEXUS_PASSWORD} \
+                -DgroupId=$GROUP_ID -DartifactId=$ARTIFACT_ID -Dversion=$VERSION \
+                -DgeneratePom=true -Dpackaging=$EXTENSION \
+                -Durl=${{env.NEXUS_PROTOCOL}}://${{env.NEXUS_SERVER_ENDPOINT}}/repository/${{vars.NEXUS_PUSH_REPOS_M2}} \
+                -Dfile=$FILE -DrepositoryId=nexus
+          }
           opsImageBuildAndPush() {
             set -e
             ./mvnw install -Dnative -DskipTests -Dquarkus.native.remote-container-build=true
@@ -1765,6 +1737,59 @@ jobs:
             python3 -m pip install -r scripts/requirements.txt --trusted-host ${{env.NEXUS_SERVER_ENDPOINT}}
             python3 -m pip list | grep harness
             deactivate
+          }
+          tsmZipBuild() {
+            set -e
+            ARTIFACT="$1"
+            requiredInputs="1"
+            validateInputs "$requiredInputs" "$@" 
+            mkdir -p build; cd tsmv101; terraform_build $PWD ../build/$ARTIFACT.zip; cd ../build; ls -l;
+            unzip -l $ARTIFACT.zip
+            cd ..
+            set +e
+          }
+          tsmZipBuildAndPush() {
+            tsmZipBuild "$@"
+            set -e
+            ARTIFACT="$1"
+            EXTENSION="$2"
+            VERSION="$3"
+            requiredInputs="1 2 3"
+            validateInputs "$requiredInputs" "$@" 
+            mvnDeploy "$ARTIFACT" "$EXTENSION" "build/$ARTIFACT.$EXTENSION" "tessell.tsm.infra" "$VERSION"
+            set +e
+          }
+          vssTarBuild() {
+            set -e
+            ARTIFACT="$1"
+            EXTENSION="$2"
+            CLOUD=$(echo "$ARTIFACT" | awk -F'[-]' '{print $3}')
+            DIR="build_$CLOUD"
+            mkdir $DIR
+            cp -r  ../tessell-vss/tessell-vss-requestor/TessellVssRequestor.exe ../tessell-vss/tessell-vss-provider/$CLOUD/install-provider $DIR
+            cd $DIR
+            tar -cf ../$ARTIFACT.$EXTENSION .
+            cd ..
+            ls
+            set +e
+          }
+          vssTarBuildAndPush() {
+            vssTarBuild "$@"
+            set -e
+            ARTIFACT="$1"
+            EXTENSION="$2"
+            mvnDeploy "$ARTIFACT" "$EXTENSION" "./$ARTIFACT.$EXTENSION" "tessell.vss" "${{env.LATEST_TAG}}"
+            set +e
+          }
+          validateInputs() {
+            local required=($1)
+            shift
+            for index in "${required[@]}"; do
+              if [ -z "${!index}" ]; then
+                echo "Error: Required Argument at index $index is null or empty."
+                exit 1
+              fi
+            done
           }
           build() {
             type="$1"
