get jira ticket ID from branch

diff --git a/.github/workflows/packer_workflow_dispatch.yml b/.github/workflows/packer_workflow_dispatch.yml
--- a/.github/workflows/packer_workflow_dispatch.yml
+++ b/.github/workflows/packer_workflow_dispatch.yml
@@ -21,7 +21,6 @@ jobs:
       NEXUS_PULL_REPOS_RAW: tessell-raw-development
       BASE_BRANCH: ${{ inputs.branchName }}
       SOFTWARE_IMAGE_BASE_RELEASE: ${{ inputs.software_image_base_release }}
-      JIRA_TICKET_ID: ${{ inputs.jira_ticket_id }}
       DESTINATION_ACCOUNT: ${{ inputs.accountId }}
       # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#using-data-from-the-triggering-workflow
       CUSTOM_TAGS: '{"TESSELL_ENVIRONMENT": "DEVELOPMENT", "GITHUB_USER": "${{ github.triggering_actor }}", "GITHUB_WORKFLOW_RUN_ID": "${{ github.run_id }}", "GITHUB_PR_BRANCH": "${{ github.ref_name }}" }'
@@ -86,6 +85,18 @@ jobs:
         id: split
         run: echo "SOFTWARE_IMAGE_BASE_LATEST_RELEASE=${SOFTWARE_IMAGE_BASE_LATEST_RELEASE##*-}" >> $GITHUB_ENV
 
+      - name: Get Tag from branch
+        id: tag_output
+        run: |
+          branch_name="${{github.ref_name}}"
+          if [[ "${branch_name}" =~ ^[^-]+-([0-9]+) ]]; then
+            version="0.0.${BASH_REMATCH[1]}"
+          else
+            echo "Error: Branch name is not in format 'TS/TDEVOPS/SRE-XXXX'"
+            exit 1
+          fi
+          echo "Jira Ticket ID: ${version}"
+          echo "JIRA_TICKET_ID=${version}" >> $GITHUB_ENV
 
       - name: Set Label
       # We do not want this workflow to run when SOURCE_BRANCH (PR_SOURCE_BRANCH) is main or "rel-*" or workflowType is "build.".
@@ -235,4 +246,4 @@ jobs:
         run: |
           curl -v -u ${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}} \
                 --upload-file ./output.json \
-                ${NEXUS_PROTOCOL}://${NEXUS_SERVER_ENDPOINT}/repository/${NEXUS_ARTIFACT_REPO}/${{ env.LABEL }}/software_image_manifest/workflow_dispatch/${{ env.SOURCE_BRANCH }}/software_image_manifest-0.0.${{ env.JIRA_TICKET_ID }}.json
+                ${NEXUS_PROTOCOL}://${NEXUS_SERVER_ENDPOINT}/repository/${NEXUS_ARTIFACT_REPO}/${{ env.LABEL }}/software_image_manifest/workflow_dispatch/${{ env.SOURCE_BRANCH }}/software_image_manifest-${{ env.JIRA_TICKET_ID }}.json
